### ISSUE TITLE
Can't represent a size of XXXXXXX in Constraints

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#482]
```=== LOGS(2022-07-28 19:36:43 UTC) ===
D/(21:34:28.908) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.56)
D/(21:34:28.918) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.62)
D/(21:34:28.926) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.67)
D/(21:34:28.929) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.73)
D/(21:34:28.933) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.79)
D/(21:34:28.936) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.84)
D/(21:34:28.940) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.9)
D/(21:34:28.943) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Uploading(totalProgress=0.96)
D/(21:34:30.886) KurobaEx-fdroid | HttpCallManager: Request (Chan4ReplyCall, https://sys.4chan.org/b/post) execution success, took 2.137289583s
D/(21:34:30.890) KurobaEx-fdroid | Chan4ReplyCall: setChan4CaptchaHeader() newCookie='Af72FOzjiFDNQhQGN-iE73hjL-FiYy_hYsXk4mLF5OJi6HRfqWuMiztDiVv2l4xa6gf_xUu5TiC5RX_znWUzr17hP3Cc3OLyKjKU7h78pjvI6_KqmatUUCo0eHqm', domain='.4chan.org', wholeCookieHeader='4chan_pass=Af72FOzjiFDNQhQGN-iE73hjL-FiYy_hYsXk4mLF5OJi6HRfqWuMiztDiVv2l4xa6gf_xUu5TiC5RX_znWUzr17hP3Cc3OLyKjKU7h78pjvI6_KqmatUUCo0eHqm; expires=Fri, 28-Jul-2023 19:34:29 GMT; Max-Age=31536000; path=/; domain=.4chan.org; secure'
D/(21:34:30.890) KurobaEx-fdroid | Chan4ReplyCall: oldCookie='Af72FOzjiFDN<cut>5YYUg-tQgVBG', newCookie='Af72FOzjiFDN<cut>matUUCo0eHqm', domain='.4chan.org'
D/(21:34:30.891) KurobaEx-fdroid | Chan4ReplyCall: setChan4CaptchaHeader() cookie is still ok. oldCookie='Af72FOzjiFDN<cut>5YYUg-tQgVBG', now=1659036870888, cookieReceivedOn=1658924899919, delta=111970969, lifetime=15552000000
D/(21:34:30.902) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=com.github.k1rakishou.chan.features.posting.ChildNotificationInfo$Status$Uploaded@c977481
D/(21:34:30.918) KurobaEx-fdroid | ReplyManager: deleteCachedDraftFromDisk(TD{4chan/b/882854386}), draftOnDisk='/data/user/0/com.github.k1rakishou.chan.fdroid/files/reply_drafts/4chan_b_882854386.json'
D/(21:34:30.918) KurobaEx-fdroid | PostingServiceDelegate: emitTerminalEvent(TD{4chan/b/882854386}, Success(replyResponse=ReplyResponse{posted=true, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='b', threadNo=882854386, postNo=882868539, password='e46b9858723402cc', probablyBanned=false, requireAuthentication=false, rateLimitInfo=null, additionalResponseData=null}, replyMode=ReplyModeSolveCaptchaManually, retrying=false))
D/(21:34:30.919) KurobaEx-fdroid | LastReplyRepository: onPostAttemptFinished(TD{4chan/b/882854386}, newCooldownInfo=null)
D/(21:34:30.919) KurobaEx-fdroid | LastReplyRepository: updateLastReplyAttemptTime(BD{4chan/b}), lastReplyTimeMs=1659036870919
D/(21:34:30.919) KurobaEx-fdroid | LastReplyRepository: onPostAttemptFinished(TD{4chan/b/882854386}, cooldownInfo=CooldownInfo(boardDescriptor=BD{4chan/b}, currentPostingCooldownMs=0))
D/(21:34:30.919) KurobaEx-fdroid | PostingServiceDelegate: SiteActions.PostResult.PostComplete(TD{4chan/b/882854386}) success
D/(21:34:30.920) KurobaEx-fdroid | LastReplyRepository: endPosting(BD{4chan/b})
D/(21:34:30.920) KurobaEx-fdroid | PostingServiceDelegate: runPostWaitQueueLoop(TD{4chan/b/882854386}) makePostInternal() -> Posted
D/(21:34:30.920) KurobaEx-fdroid | PostingServiceDelegate: runPostQueueLoop(TD{4chan/b/882854386}) took 2177ms
D/(21:34:30.920) KurobaEx-fdroid | PostingServiceDelegate: All replies for board BD{4chan/b} processed, resetting the cooldowns
D/(21:34:30.920) KurobaEx-fdroid | LastReplyRepository: onPostAttemptFinished(TD{4chan/b/882854386}, newCooldownInfo=null)
D/(21:34:30.920) KurobaEx-fdroid | LastReplyRepository: onPostAttemptFinished(TD{4chan/b/882854386}, cooldownInfo=CooldownInfo(boardDescriptor=BD{4chan/b}, currentPostingCooldownMs=0))
D/(21:34:30.921) KurobaEx-fdroid | PostingServiceDelegate: All replies processed, stopping the service
D/(21:34:30.922) KurobaEx-fdroid | ReplyPresenter: processPostingStatusUpdates(TD{4chan/b/882854386}) -> AfterPosting, status.postResult=Success(replyResponse=ReplyResponse{posted=true, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='b', threadNo=882854386, postNo=882868539, password='e46b9858723402cc', probablyBanned=false, requireAuthentication=false, rateLimitInfo=null, additionalResponseData=null}, replyMode=ReplyModeSolveCaptchaManually, retrying=false)
D/(21:34:30.924) KurobaEx-fdroid | ReplyPresenter: onPostComplete() posted==true replyResponse=ReplyResponse{posted=true, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='b', threadNo=882854386, postNo=882868539, password='e46b9858723402cc', probablyBanned=false, requireAuthentication=false, rateLimitInfo=null, additionalResponseData=null}
D/(21:34:30.924) KurobaEx-fdroid | ReplyPresenter: prevChanDescriptor() prevChanDescriptor=TD{4chan/b/882854386}, siteDescriptor=SD{4chan}, replyResponse=ReplyResponse{posted=true, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='b', threadNo=882854386, postNo=882868539, password='e46b9858723402cc', probablyBanned=false, requireAuthentication=false, rateLimitInfo=null, additionalResponseData=null}
D/(21:34:30.931) KurobaEx-fdroid | ThreadListLayout: openReply() open: false
D/(21:34:30.933) KurobaEx-fdroid | ChanTicker: resetEverythingAndKickTicker()
D/(21:34:30.933) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(21:34:30.933) KurobaEx-fdroid | ReplyPresenter: processPostingStatusUpdates(TD{4chan/b/882854386}) consumeTerminalEvent(TD{4chan/b/882854386})
D/(21:34:30.933) KurobaEx-fdroid | PostingServiceDelegate: consumeTerminalEvent(TD{4chan/b/882854386}) consumed=true
D/(21:34:30.933) KurobaEx-fdroid | ReplyPresenter: processPostingStatusUpdates(TD{4chan/b/882854386}) -> Attached
D/(21:34:30.934) KurobaEx-fdroid | PostingService: childNotificationUpdates() descriptor=TD{4chan/b/882854386}, status=Posted(chanDescriptor=TD{4chan/b/882854386})
D/(21:34:30.939) KurobaEx-fdroid | PostingService: mainNotificationUpdates() activeRepliesCount=0
D/(21:34:30.942) KurobaEx-fdroid | PostingService: Got StopService command, stopping the service
D/(21:34:30.949) KurobaEx-fdroid | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/b/882854386}
D/(21:34:30.950) KurobaEx-fdroid | PostingService: onDestroy()
D/(21:34:30.950) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/b/882854386}, waiting 0ms
D/(21:34:30.950) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action begin
D/(21:34:30.950) KurobaEx-fdroid | ThreadPresenter: onChanTickerTick(TD{4chan/b/882854386})
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: normalLoad() start
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/b/882854386}
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: showLoading=false
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(21:34:30.951) KurobaEx-fdroid | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(21:34:30.951) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action end


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.IllegalArgumentException: Can't represent a size of 357913942 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:3)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit_release(Constraints.kt:2)
	at androidx.compose.foundation.lazy.LazyGridKt$ItemRow$2.measure-3p2s80s(LazyGrid.kt:18)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:13)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:52)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:30)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:23)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.foundation.lazy.layout.LazyLayoutPlaceablesProvider.getAndMeasure-0kLqBqw(LazyMeasurePolicy.kt:7)
	at androidx.compose.foundation.lazy.list.LazyListKt$rememberLazyListMeasurePolicy$1$1.measure-3p2s80s(LazyList.kt:78)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2.invoke(LazyLayout.kt:16)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:19)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:13)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.foundation.layout.WrapContentModifier.measure-3p2s80s(Size.kt:8)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:12)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:52)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:30)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:23)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:10)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke(BoxWithConstraints.kt:6)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:19)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:13)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:12)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:52)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:30)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:23)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImpl.kt:43)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:13)
	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:12)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:52)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:30)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:23)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(RootMeasurePolicy.kt:4)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:13)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:11)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:50)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:30)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:11)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:13)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:23)
	at android.view.View.measure(View.java:25787)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:7)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:2)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25787)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:55)
	at com.github.k1rakishou.chan.ui.layout.DrawerWidthAdjustingLayout.onMeasure(DrawerWidthAdjustingLayout.java:8)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:828)
	at android.view.View.measure(View.java:25787)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3774)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2532)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2794)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2252)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8791)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1137)
	at android.view.Choreographer.doCallbacks(Choreographer.java:959)
	at android.view.Choreographer.doFrame(Choreographer.java:884)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1122)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8219)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)


------------------------------
Android API Level: 30
App Version: v1.3.10
Phone Model: realme RMX1931
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 384
App running time: 00:07:46.001
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 11; RMX1931 Build/RKQ1.200928.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.10
maxPostsCountInPostsCache: 16000
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: null
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment]
Seems like after updating compose this https://github.com/KurobaExReports/Reports/issues/504 is the same crash but with more descriptive message. Gonna close this one.
