### ISSUE TITLE
java.lang.RuntimeException Unable to destroy activity {com.github.k1rakishou.chan.beta/com.github.k1rakishou.chan.activity.CrashReportActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#496]
Stacktrace
```
java.lang.RuntimeException: Unable to destroy activity {com.github.k1rakishou.chan.beta/com.github.k1rakishou.chan.activity.CrashReportActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized
	at com.github.k1rakishou.chan.activity.CrashReportActivity.getAppRestarter(CrashReportActivity.kt:1)
	at com.github.k1rakishou.chan.activity.CrashReportActivity.onDestroy(CrashReportActivity.kt:2)
	at android.app.Activity.performDestroy(Activity.java:7218)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
	... 9 more

```

Logs
```
D/(03:16:42.275) KurobaEx-beta | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(03:16:42.306) KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_dark.json) does not exist on the disk
D/(03:16:42.306) KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_light.json) does not exist on the disk
D/(03:16:42.313) KurobaEx-beta | ChanPostRepository: ChanPostRepository.initialize()
D/(03:16:42.324) KurobaEx-beta | SiteManager: SiteManager.initialize()
D/(03:16:42.324) KurobaEx-beta | BoardManager: BoardManager.initialize()
D/(03:16:42.324) KurobaEx-beta | SiteManager: loadSitesInternal() start
D/(03:16:42.325) KurobaEx-beta | BookmarksManager: BookmarksManager.initialize()
D/(03:16:42.325) KurobaEx-beta | BoardManager: loadBoardsInternal() start
D/(03:16:42.325) KurobaEx-beta | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(03:16:42.326) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() start
D/(03:16:42.327) KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(03:16:42.327) KurobaEx-beta | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(03:16:42.328) KurobaEx-beta | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(03:16:42.329) KurobaEx-beta | ArchivesManager: ArchivesManager.initialize()
D/(03:16:42.330) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() start
D/(03:16:42.334) KurobaEx-beta | ChanFilterManager: ChanFilterManager.initialize()
D/(03:16:42.335) KurobaEx-beta | Chan: Application initialization took 160ms
D/(03:16:42.336) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() start
D/(03:16:42.348) KurobaEx-beta | ChanPostRepository: deleteOldPostsIfNeeded database is empty
D/(03:16:42.351) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(03:16:42.351) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithValue() called
D/(03:16:42.352) KurobaEx-beta | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.352) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithValue() done
D/(03:16:42.352) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(03:16:42.354) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() end, took 22.326961ms
D/(03:16:42.366) KurobaEx-beta | CrashReportActivity: CrashReportActivity launched
D/(03:16:42.370) KurobaEx-beta | BookmarksRepository: initialize() -> 0 took 4.354130ms
D/(03:16:42.373) KurobaEx-beta | BookmarksManager: SuspendableInitializer initWithValue() called
D/(03:16:42.373) KurobaEx-beta | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.373) KurobaEx-beta | BookmarksManager: SuspendableInitializer initWithValue() done
D/(03:16:42.373) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() done. Loaded 0 bookmarks and 0 active bookmarks
D/(03:16:42.373) KurobaEx-beta | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(03:16:42.374) KurobaEx-beta | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.374) KurobaEx-beta | ChanFilterManager: SuspendableInitializer initWithValue() done
E/(03:16:42.374) KurobaEx-beta | CrashReportActivity: Got new exception: java.lang.RuntimeException
D/(03:16:42.374) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(03:16:42.374) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() end, took 38.061963ms
D/(03:16:42.375) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() end, took 49.114567ms
D/(03:16:42.380) KurobaEx-beta | Chan: ^^^ App went foreground ^^^
D/(03:16:42.380) KurobaEx-beta | ApplicationVisibilityManager: onEnteredForeground() callback execution took 31.956us, callbacks count: 2
D/(03:16:42.381) KurobaEx-beta | SiteRepository: initializeSites() -> 24 took 5.592738ms
D/(03:16:42.382) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(03:16:42.382) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(03:16:42.382) KurobaEx-beta | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.382) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(03:16:42.382) KurobaEx-beta | SiteRepository: allSitesLoadedInitializer initialized
D/(03:16:42.394) KurobaEx-beta | ChanPostRepository: deleteOldThreadsIfNeeded database is empty
D/(03:16:42.394) KurobaEx-beta | BookmarksManager: persistBookmarks async called
D/(03:16:42.395) KurobaEx-beta | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(03:16:42.395) KurobaEx-beta | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.395) KurobaEx-beta | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(03:16:42.403) KurobaEx-beta | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(03:16:42.412) KurobaEx-beta | LynxchanSite: Using domain: 'https://endchan.net/'
D/(03:16:42.415) KurobaEx-beta | ThreadBookmarkLocalSource: persist(0)
D/(03:16:42.418) KurobaEx-beta | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(03:16:42.419) KurobaEx-beta | BookmarksRepository: persist(0) took 7.345927ms
D/(03:16:42.460) KurobaEx-beta | Dvach: Using domain: 'https://2ch.hk/'
D/(03:16:42.493) KurobaEx-beta | SiteManager: SuspendableInitializer initWithValue() called
D/(03:16:42.493) KurobaEx-beta | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.493) KurobaEx-beta | SiteManager: SuspendableInitializer initWithValue() done
D/(03:16:42.493) KurobaEx-beta | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(03:16:42.493) KurobaEx-beta | SiteManager: loadSitesInternal() end, took 168.768403ms
D/(03:16:42.493) KurobaEx-beta | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(03:16:42.496) KurobaEx-beta | BoardRepository: loadAllBoards() -> 0 took 500.639us
D/(03:16:42.497) KurobaEx-beta | BoardManager: SuspendableInitializer initWithValue() called
D/(03:16:42.497) KurobaEx-beta | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(03:16:42.497) KurobaEx-beta | BoardManager: SuspendableInitializer initWithValue() done
D/(03:16:42.497) KurobaEx-beta | BoardManager: loadBoardsInternal() done. Loaded 0 boards
D/(03:16:42.497) KurobaEx-beta | BoardManager: loadBoardsInternal() end, took 171.477620ms
D/(03:16:43.594) KurobaEx-beta | BookmarksManager: subscriptions=2
D/(03:16:43.594) KurobaEx-beta | BookmarksManager: persistBookmarks async finished
D/(03:16:43.665) KurobaEx-beta | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(03:16:43.667) KurobaEx-beta | BookmarkWatcherCoordinator: Calling onBookmarksChanged() because bookmarks have actually changed
D/(03:16:43.667) KurobaEx-beta | BookmarkWatcherCoordinator: onBookmarksChanged() start hasCreateBookmarkChange: false, alreadyRunning: false
D/(03:16:43.677) KurobaEx-beta | ThreadBookmarkGroupRepository: initialize() -> 1 took 2.401292ms
D/(03:16:43.678) KurobaEx-beta | BookmarkWatcherCoordinator: onBookmarksChanged() no active bookmarks, nothing to do
D/(03:16:43.679) KurobaEx-beta | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(03:16:43.681) KurobaEx-beta | BookmarkWatcherCoordinator: onBookmarksChanged() end
D/(03:16:43.681) KurobaEx-beta | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(03:16:43.681) KurobaEx-beta | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 15.971373ms
W/(03:16:43.710) KurobaEx-beta | StartActivity: Can not save instance state, the board loadable is null
D/(03:16:43.711) KurobaEx-beta | Chan: vvv App went background vvv
D/(03:16:43.712) KurobaEx-beta | BookmarksManager: persistBookmarks eager called
E/(03:16:43.712) KurobaEx-beta | ThreadPresenter: isBound() currentChanDescriptor == null
D/(03:16:43.716) KurobaEx-beta | ReplyManager: persistDrafts() drafts are empty
D/(03:16:43.716) KurobaEx-beta | ReplyManager: persistDrafts() took 4.017243ms
D/(03:16:43.717) KurobaEx-beta | ApplicationVisibilityManager: onEnteredBackground() callback execution took 5.614893ms, callbacks count: 4
D/(03:16:43.717) KurobaEx-beta | StartActivity: stop
D/(03:16:43.722) KurobaEx-beta | ThreadBookmarkLocalSource: persist(0)
D/(03:16:43.726) KurobaEx-beta | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(03:16:43.726) KurobaEx-beta | BookmarksRepository: persist(0) took 4.049019ms
D/(03:16:43.729) KurobaEx-beta | BookmarksManager: persistBookmarks eager finished
D/(03:16:43.730) KurobaEx-beta | HistoryNavigationManager: persistNavigationStack async called
D/(03:16:43.730) KurobaEx-beta | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=0
D/(03:16:43.732) KurobaEx-beta | NavHistoryLocalSource: persist(navHistoryStack.size=0)
D/(03:16:43.733) KurobaEx-beta | HistoryNavigationRepository: persist(0) took 528.211us
D/(03:16:43.734) KurobaEx-beta | HistoryNavigationManager: persistNavigationStack async finished

```
Additional information
```
------------------------------
Android API Level: 27
App Version: v1.3.12
Phone Model: LGE Nexus 5X
Build type: Release
Flavor type: Beta
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 512
App running time: 00:00:04.056
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 8.1.0; Nexus 5X Build/OSM1.180201.031; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-beta v1.3.12
maxPostsCountInPostsCache: 16000
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: null
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/d0adbea1cbdcc07d46e4c1c113b96f8f0564f90a
