### ISSUE TITLE
java.lang.NoClassDefFoundError com.github.k1rakishou.chan.core.cache.downloader.DownloaderUtils

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#537]
Stacktrace
```
java.lang.NoClassDefFoundError: com.github.k1rakishou.chan.core.cache.downloader.DownloaderUtils
	at com.github.k1rakishou.chan.core.cache.downloader.ChunkDownloader$downloadChunk$2$1.onFailure(ChunkDownloader.kt:11)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:19)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```

Logs
```
D/(18:17:19.074) KurobaEx-fdroid | ChunkReader: [NormalFileCacheV2Thread-0]: handleErrors(0) (https://i.4cdn.org/d/1660099344656379.jpg) cancel for chunk 0..323899
E/(18:17:19.082) KurobaEx-fdroid | Chan: Unhandled exception in thread: main
E/(18:17:19.082) KurobaEx-fdroid | Chan: java.lang.OutOfMemoryError: Failed to allocate a 12 byte allocation with 3416 free bytes and 3KB until OOM
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.os.ICustomFrequencyManager$Stub.asInterface(ICustomFrequencyManager.java:31)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.GestureDetector.triggerGDBoost(GestureDetector.java:710)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:668)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.media_viewer.media_view.FullImageMediaView$$ExternalSyntheticLambda1.onTouch(Unknown Source)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.View.dispatchTouchEvent(View.java:10012)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2869)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.media_viewer.MediaViewerActivity.dispatchTouchEvent(MediaViewerActivity.kt:2)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2830)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.View.dispatchPointerEvent(View.java:10253)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5523)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5359)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4964)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5021)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4857)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4823)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4831)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4804)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7525)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7393)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7354)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7635)
E/(18:17:19.082) KurobaEx-fdroid | Chan: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceive
D/(18:17:19.260) KurobaEx-fdroid | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Couldn't get chunk response, reason = IOException (canceled due to java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available) (https://i.4cdn.org/d/1660099344656379.jpg) 323900..647800, time = 17866ms
E/(18:17:19.260) KurobaEx-fdroid | Chan: Unhandled exception in thread: OkHttp Dispatcher
E/(18:17:19.260) KurobaEx-fdroid | Chan: java.lang.NoClassDefFoundError: com.github.k1rakishou.chan.core.cache.downloader.DownloaderUtils
E/(18:17:19.260) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.core.cache.downloader.ChunkDownloader$downloadChunk$2$1.onFailure(ChunkDownloader.kt:11)
E/(18:17:19.260) KurobaEx-fdroid | Chan: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:19)
E/(18:17:19.260) KurobaEx-fdroid | Chan: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/(18:17:19.260) KurobaEx-fdroid | Chan: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/(18:17:19.260) KurobaEx-fdroid | Chan: 	at java.lang.Thread.run(Thread.java:818)
D/(18:17:21.372) KurobaEx-fdroid | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(18:17:21.461) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_dark.json) does not exist on the disk
D/(18:17:21.461) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_light.json) does not exist on the disk
D/(18:17:21.516) KurobaEx-fdroid | ChanPostRepository: ChanPostRepository.initialize()
D/(18:17:21.570) KurobaEx-fdroid | SiteManager: SiteManager.initialize()
D/(18:17:21.572) KurobaEx-fdroid | BoardManager: BoardManager.initialize()
D/(18:17:21.572) KurobaEx-fdroid | SiteManager: loadSitesInternal() start
D/(18:17:21.574) KurobaEx-fdroid | BoardManager: loadBoardsInternal() start
D/(18:17:21.574) KurobaEx-fdroid | BookmarksManager: BookmarksManager.initialize()
D/(18:17:21.576) KurobaEx-fdroid | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(18:17:21.577) KurobaEx-fdroid | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(18:17:21.578) KurobaEx-fdroid | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(18:17:21.578) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() start
D/(18:17:21.578) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(18:17:21.580) KurobaEx-fdroid | ArchivesManager: ArchivesManager.initialize()
D/(18:17:21.580) KurobaEx-fdroid | ChanFilterManager: ChanFilterManager.initialize()
D/(18:17:21.581) KurobaEx-fdroid | Chan: Application initialization took 1657ms
D/(18:17:21.583) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() start
D/(18:17:21.580) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() start
D/(18:17:21.640) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(18:17:21.641) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() called
D/(18:17:21.642) KurobaEx-fdroid | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.642) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() done
D/(18:17:21.643) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(18:17:21.650) KurobaEx-fdroid | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 8843, max allowed posts amount: 75000
D/(18:17:21.654) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() end, took 55.075781ms
D/(18:17:21.670) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(18:17:21.671) KurobaEx-fdroid | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.671) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(18:17:21.671) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(18:17:21.671) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() end, took 88.389583ms
D/(18:17:21.681) KurobaEx-fdroid | SiteRepository: initializeSites() -> 24 took 9.467917ms
D/(18:17:21.685) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(18:17:21.685) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(18:17:21.685) KurobaEx-fdroid | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.685) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(18:17:21.686) KurobaEx-fdroid | SiteRepository: allSitesLoadedInitializer initialized
D/(18:17:21.710) KurobaEx-fdroid | BookmarksRepository: initialize() -> 5 took 24.796979ms
D/(18:17:21.712) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() called
D/(18:17:21.712) KurobaEx-fdroid | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.712) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() done
D/(18:17:21.712) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() done. Loaded 5 bookmarks and 5 active bookmarks
D/(18:17:21.713) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() end, took 135.410938ms
D/(18:17:21.733) KurobaEx-fdroid | CrashReportActivity: CrashReportActivity launched
D/(18:17:21.752) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(18:17:21.763) KurobaEx-fdroid | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 8843, max allowed threads amount: 12500
D/(18:17:21.764) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://endchan.net/'
D/(18:17:21.764) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(18:17:21.764) KurobaEx-fdroid | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.765) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() done
E/(18:17:21.777) KurobaEx-fdroid | CrashReportActivity: Got new exception: java.lang.NoClassDefFoundError
D/(18:17:21.808) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(18:17:21.808) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 33.959us, callbacks count: 2
D/(18:17:21.872) KurobaEx-fdroid | Dvach: Using domain: 'https://2ch.hk/'
D/(18:17:21.876) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(18:17:21.879) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(5)
D/(18:17:21.889) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(18:17:21.889) KurobaEx-fdroid | BookmarksRepository: persist(5) took 10.761458ms
D/(18:17:21.897) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(18:17:21.897) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(18:17:21.897) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.897) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(18:17:21.898) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(18:17:21.898) KurobaEx-fdroid | SiteManager: loadSitesInternal() end, took 323.600573ms
D/(18:17:21.918) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 78 took 15.069010ms
D/(18:17:21.919) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(18:17:21.920) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:17:21.920) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(18:17:21.920) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 78 boards
D/(18:17:21.920) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 345.778177ms
D/(18:17:22.522) KurobaEx-fdroid | BookmarksManager: subscriptions=2
D/(18:17:22.522) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(18:17:22.927) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(18:17:22.934) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(18:17:22.934) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(18:17:22.985) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 1 took 55.209479ms
D/(18:17:22.987) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(18:17:22.987) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 60.156615ms

```
Additional information
```
------------------------------
Android API Level: 23
App Version: v1.3.13
Phone Model: samsung SM-S727VL
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: true, isLowRamDeviceForced: false
MemoryClass: 96
App running time: 00:00:07.162
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 6.0.1; SM-S727VL Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.13
maxPostsCountInPostsCache: 5000
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/7FC4-1412%3A
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment]
OOM
