### ISSUE TITLE
java.lang.RuntimeException Unable to destroy activity {com.github.k1rakishou.chan/com.github.k1rakishou.chan.activity.StartActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#560]
Stacktrace
```
java.lang.RuntimeException: Unable to destroy activity {com.github.k1rakishou.chan/com.github.k1rakishou.chan.activity.StartActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5495)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5528)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8085)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized
	at com.github.k1rakishou.chan.activity.StartActivity.onDestroy(StartActivity.kt:34)
	at android.app.Activity.performDestroy(Activity.java:8544)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5482)
	... 13 more

```

Logs
```
D/(04:56:04.157) KurobaEx | SiteManager: SiteManager.initialize()
D/(04:56:04.157) KurobaEx | BoardManager: BoardManager.initialize()
D/(04:56:04.157) KurobaEx | BookmarksManager: BookmarksManager.initialize()
D/(04:56:04.158) KurobaEx | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(04:56:04.158) KurobaEx | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(04:56:04.158) KurobaEx | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(04:56:04.158) KurobaEx | ArchivesManager: ArchivesManager.initialize()
D/(04:56:04.158) KurobaEx | ChanFilterManager: ChanFilterManager.initialize()
D/(04:56:04.158) KurobaEx | SiteManager: loadSitesInternal() start
D/(04:56:04.158) KurobaEx | BoardManager: loadBoardsInternal() start
D/(04:56:04.158) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(04:56:04.159) KurobaEx | Chan: Application initialization took 144ms
D/(04:56:04.159) KurobaEx | BookmarksManager: initializeBookmarksInternal() start
D/(04:56:04.160) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() start
D/(04:56:04.161) KurobaEx | ChanFilterManager: loadFiltersInternal() start
D/(04:56:04.168) KurobaEx | CrashReportActivity: CrashReportActivity launched
E/(04:56:04.172) KurobaEx | CrashReportActivity: Got new exception: java.lang.RuntimeException
D/(04:56:04.175) KurobaEx | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(04:56:04.175) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() called
D/(04:56:04.176) KurobaEx | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.176) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() done
D/(04:56:04.176) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(04:56:04.176) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() end, took 15.376354ms
D/(04:56:04.182) KurobaEx | SiteRepository: initializeSites() -> 24 took 1.106979ms
D/(04:56:04.182) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(04:56:04.182) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(04:56:04.182) KurobaEx | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.182) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(04:56:04.182) KurobaEx | SiteRepository: allSitesLoadedInitializer initialized
D/(04:56:04.184) KurobaEx | Chan: ^^^ App went foreground ^^^
D/(04:56:04.184) KurobaEx | ApplicationVisibilityManager: onEnteredForeground() callback execution took 19.271us, callbacks count: 2
D/(04:56:04.188) KurobaEx | BookmarksRepository: initialize() -> 1 took 5.218333ms
D/(04:56:04.189) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() called
D/(04:56:04.189) KurobaEx | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.189) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() done
D/(04:56:04.189) KurobaEx | BookmarksManager: initializeBookmarksInternal() done. Loaded 1 bookmarks and 1 active bookmarks
D/(04:56:04.189) KurobaEx | BookmarksManager: initializeBookmarksInternal() end, took 30.703802ms
D/(04:56:04.190) KurobaEx | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 166, max allowed posts amount: 75000
D/(04:56:04.191) KurobaEx | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(04:56:04.191) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(04:56:04.191) KurobaEx | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.191) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(04:56:04.191) KurobaEx | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(04:56:04.192) KurobaEx | ChanFilterManager: loadFiltersInternal() end, took 29.765261ms
D/(04:56:04.192) KurobaEx | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 166, max allowed threads amount: 12500
D/(04:56:04.192) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(04:56:04.192) KurobaEx | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.192) KurobaEx | LynxchanSite: Using domain: 'https://endchan.net/'
D/(04:56:04.192) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(04:56:04.210) KurobaEx | Dvach: Using domain: 'https://2ch.hk/'
D/(04:56:04.214) KurobaEx | SiteManager: SuspendableInitializer initWithValue() called
D/(04:56:04.214) KurobaEx | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.214) KurobaEx | SiteManager: SuspendableInitializer initWithValue() done
D/(04:56:04.214) KurobaEx | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(04:56:04.214) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(04:56:04.214) KurobaEx | SiteManager: loadSitesInternal() end, took 56.013177ms
D/(04:56:04.222) KurobaEx | BoardRepository: loadAllBoards() -> 78 took 6.735625ms
D/(04:56:04.223) KurobaEx | BoardManager: SuspendableInitializer initWithValue() called
D/(04:56:04.223) KurobaEx | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:04.223) KurobaEx | BoardManager: SuspendableInitializer initWithValue() done
D/(04:56:04.224) KurobaEx | BoardManager: loadBoardsInternal() done. Loaded 78 boards
D/(04:56:04.224) KurobaEx | BoardManager: loadBoardsInternal() end, took 65.122136ms
D/(04:56:04.231) KurobaEx | BookmarksManager: persistBookmarks async called
D/(04:56:04.233) KurobaEx | ThreadBookmarkLocalSource: persist(1)
D/(04:56:04.241) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(04:56:04.241) KurobaEx | BookmarksRepository: persist(1) took 8.639010ms
D/(04:56:04.380) KurobaEx | BookmarksManager: subscriptions=2
D/(04:56:04.380) KurobaEx | BookmarksManager: persistBookmarks async finished
D/(04:56:04.399) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(04:56:04.401) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(04:56:04.401) KurobaEx | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(04:56:04.407) KurobaEx | ThreadBookmarkGroupRepository: initialize() -> 1 took 1.344792ms
D/(04:56:04.408) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(04:56:04.408) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 8.551562ms
D/(04:56:07.354) KurobaEx | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(04:56:07.362) KurobaEx | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan/files/kurobaex_theme_dark.json) does not exist on the disk
D/(04:56:07.362) KurobaEx | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan/files/kurobaex_theme_light.json) does not exist on the disk
D/(04:56:07.364) KurobaEx | ChanPostRepository: ChanPostRepository.initialize()
D/(04:56:07.369) KurobaEx | SiteManager: SiteManager.initialize()
D/(04:56:07.369) KurobaEx | BoardManager: BoardManager.initialize()
D/(04:56:07.369) KurobaEx | SiteManager: loadSitesInternal() start
D/(04:56:07.369) KurobaEx | BookmarksManager: BookmarksManager.initialize()
D/(04:56:07.369) KurobaEx | BoardManager: loadBoardsInternal() start
D/(04:56:07.370) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(04:56:07.370) KurobaEx | BookmarksManager: initializeBookmarksInternal() start
D/(04:56:07.370) KurobaEx | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(04:56:07.370) KurobaEx | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(04:56:07.370) KurobaEx | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(04:56:07.370) KurobaEx | ArchivesManager: ArchivesManager.initialize()
D/(04:56:07.371) KurobaEx | ChanFilterManager: ChanFilterManager.initialize()
D/(04:56:07.371) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() start
D/(04:56:07.371) KurobaEx | Chan: Application initialization took 110ms
D/(04:56:07.372) KurobaEx | ChanFilterManager: loadFiltersInternal() start
D/(04:56:07.374) KurobaEx | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(04:56:07.374) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() called
D/(04:56:07.374) KurobaEx | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.374) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() done
D/(04:56:07.374) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(04:56:07.374) KurobaEx | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 166, max allowed posts amount: 75000
D/(04:56:07.375) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() end, took 3.699844ms
D/(04:56:07.378) KurobaEx | BookmarksRepository: initialize() -> 1 took 1.608229ms
D/(04:56:07.378) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() called
D/(04:56:07.379) KurobaEx | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.379) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() done
D/(04:56:07.379) KurobaEx | BookmarksManager: initializeBookmarksInternal() done. Loaded 1 bookmarks and 1 active bookmarks
D/(04:56:07.379) KurobaEx | BookmarksManager: initializeBookmarksInternal() end, took 9.004062ms
D/(04:56:07.379) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(04:56:07.379) KurobaEx | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.379) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(04:56:07.379) KurobaEx | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(04:56:07.380) KurobaEx | ChanFilterManager: loadFiltersInternal() end, took 7.267083ms
W/(04:56:07.380) KurobaEx | StartActivity: Workaround for intent mismatch.
D/(04:56:07.380) KurobaEx | SiteRepository: initializeSites() -> 24 took 1.020782ms
D/(04:56:07.381) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(04:56:07.381) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(04:56:07.381) KurobaEx | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.381) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(04:56:07.381) KurobaEx | SiteRepository: allSitesLoadedInitializer initialized
D/(04:56:07.382) KurobaEx | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 166, max allowed threads amount: 12500
D/(04:56:07.382) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(04:56:07.382) KurobaEx | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.382) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(04:56:07.384) KurobaEx | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(04:56:07.385) KurobaEx | LynxchanSite: Using domain: 'https://endchan.net/'
D/(04:56:07.388) KurobaEx | StartActivity: onCreate() intentMismatchWorkaround()==true, savedInstanceState == null: true
D/(04:56:07.396) KurobaEx | Dvach: Using domain: 'https://2ch.hk/'
D/(04:56:07.396) KurobaEx | BookmarksManager: persistBookmarks async called
D/(04:56:07.397) KurobaEx | ThreadBookmarkLocalSource: persist(1)
D/(04:56:07.399) KurobaEx | SiteManager: SuspendableInitializer initWithValue() called
D/(04:56:07.399) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(04:56:07.399) KurobaEx | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.399) KurobaEx | SiteManager: SuspendableInitializer initWithValue() done
D/(04:56:07.399) KurobaEx | BookmarksRepository: persist(1) took 1.919063ms
D/(04:56:07.399) KurobaEx | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(04:56:07.399) KurobaEx | SiteManager: loadSitesInternal() end, took 29.946354ms
D/(04:56:07.399) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(04:56:07.407) KurobaEx | BoardRepository: loadAllBoards() -> 78 took 2.358697ms
D/(04:56:07.408) KurobaEx | BookmarksManager: subscriptions=2
D/(04:56:07.408) KurobaEx | BookmarksManager: persistBookmarks async finished
D/(04:56:07.408) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(04:56:07.408) KurobaEx | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(04:56:07.408) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(04:56:07.409) KurobaEx | BoardManager: SuspendableInitializer initWithValue() called
D/(04:56:07.409) KurobaEx | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:07.409) KurobaEx | BoardManager: SuspendableInitializer initWithValue() done
D/(04:56:07.409) KurobaEx | BoardManager: loadBoardsInternal() done. Loaded 78 boards
D/(04:56:07.409) KurobaEx | BoardManager: loadBoardsInternal() end, took 39.674531ms
D/(04:56:07.414) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(04:56:07.418) KurobaEx | ThreadBookmarkGroupRepository: initialize() -> 1 took 3.801615ms
D/(04:56:07.420) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(04:56:07.420) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 11.330521ms
D/(04:56:07.422) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(04:56:08.031) KurobaEx | StartActivity: onDestroy()
E/(04:56:08.036) KurobaEx | Chan: Unhandled exception in thread: main
E/(04:56:08.036) KurobaEx | Chan: java.lang.RuntimeException: Unable to destroy activity {com.github.k1rakishou.chan/com.github.k1rakishou.chan.activity.StartActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5495)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5528)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
E/(04:56:08.036) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/(04:56:08.036) KurobaEx | Chan: 	at android.os.Looper.loopOnce(Looper.java:210)
E/(04:56:08.036) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:299)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8085)
E/(04:56:08.036) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(04:56:08.036) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/(04:56:08.036) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/(04:56:08.036) KurobaEx | Chan: Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appRestarter has not been initialized
E/(04:56:08.036) KurobaEx | Chan: 	at com.github.k1rakishou.chan.activity.StartActivity.onDestroy(StartActivity.kt:34)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.Activity.performDestroy(Activity.java:8544)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
E/(04:56:08.036) KurobaEx | Chan: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5482)
E/(04:56:08.036) KurobaEx | Chan: 	... 13 more
D/(04:56:08.226) KurobaEx | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(04:56:08.233) KurobaEx | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan/files/kurobaex_theme_dark.json) does not exist on the disk
D/(04:56:08.233) KurobaEx | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan/files/kurobaex_theme_light.json) does not exist on the disk
D/(04:56:08.235) KurobaEx | ChanPostRepository: ChanPostRepository.initialize()
D/(04:56:08.239) KurobaEx | SiteManager: SiteManager.initialize()
D/(04:56:08.239) KurobaEx | BoardManager: BoardManager.initialize()
D/(04:56:08.239) KurobaEx | SiteManager: loadSitesInternal() start
D/(04:56:08.239) KurobaEx | BookmarksManager: BookmarksManager.initialize()
D/(04:56:08.239) KurobaEx | BoardManager: loadBoardsInternal() start
D/(04:56:08.239) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(04:56:08.239) KurobaEx | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(04:56:08.240) KurobaEx | BookmarksManager: initializeBookmarksInternal() start
D/(04:56:08.240) KurobaEx | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(04:56:08.240) KurobaEx | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(04:56:08.240) KurobaEx | ArchivesManager: ArchivesManager.initialize()
D/(04:56:08.240) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() start
D/(04:56:08.241) KurobaEx | ChanFilterManager: ChanFilterManager.initialize()
D/(04:56:08.241) KurobaEx | Chan: Application initialization took 108ms
D/(04:56:08.241) KurobaEx | ChanFilterManager: loadFiltersInternal() start
D/(04:56:08.248) KurobaEx | CrashReportActivity: CrashReportActivity launched
D/(04:56:08.249) KurobaEx | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 166, max allowed posts amount: 75000
D/(04:56:08.250) KurobaEx | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(04:56:08.250) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() called
D/(04:56:08.250) KurobaEx | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.250) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() done
D/(04:56:08.250) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(04:56:08.250) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() end, took 9.801875ms
E/(04:56:08.252) KurobaEx | CrashReportActivity: Got new exception: java.lang.RuntimeException
D/(04:56:08.252) KurobaEx | BookmarksRepository: initialize() -> 1 took 1.261666ms
D/(04:56:08.252) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() called
D/(04:56:08.252) KurobaEx | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.252) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() done
D/(04:56:08.252) KurobaEx | BookmarksManager: initializeBookmarksInternal() done. Loaded 1 bookmarks and 1 active bookmarks
D/(04:56:08.253) KurobaEx | BookmarksManager: initializeBookmarksInternal() end, took 13.702709ms
D/(04:56:08.254) KurobaEx | SiteRepository: initializeSites() -> 24 took 1.089322ms
D/(04:56:08.254) KurobaEx | Chan: ^^^ App went foreground ^^^
D/(04:56:08.254) KurobaEx | ApplicationVisibilityManager: onEnteredForeground() callback execution took 10.416us, callbacks count: 2
D/(04:56:08.254) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(04:56:08.255) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(04:56:08.255) KurobaEx | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.255) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(04:56:08.255) KurobaEx | SiteRepository: allSitesLoadedInitializer initialized
D/(04:56:08.256) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(04:56:08.256) KurobaEx | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 166, max allowed threads amount: 12500
D/(04:56:08.256) KurobaEx | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.256) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(04:56:08.256) KurobaEx | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(04:56:08.256) KurobaEx | ChanFilterManager: loadFiltersInternal() end, took 14.531145ms
D/(04:56:08.256) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(04:56:08.256) KurobaEx | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.256) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(04:56:08.257) KurobaEx | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(04:56:08.260) KurobaEx | LynxchanSite: Using domain: 'https://endchan.net/'
D/(04:56:08.267) KurobaEx | BookmarksManager: persistBookmarks async called
D/(04:56:08.268) KurobaEx | ThreadBookmarkLocalSource: persist(1)
D/(04:56:08.268) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(04:56:08.268) KurobaEx | BookmarksRepository: persist(1) took 725.157us
D/(04:56:08.270) KurobaEx | BookmarksManager: subscriptions=2
D/(04:56:08.270) KurobaEx | BookmarksManager: persistBookmarks async finished
D/(04:56:08.271) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(04:56:08.271) KurobaEx | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(04:56:08.271) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(04:56:08.272) KurobaEx | Dvach: Using domain: 'https://2ch.hk/'
D/(04:56:08.274) KurobaEx | ThreadBookmarkGroupRepository: initialize() -> 1 took 1.216615ms
D/(04:56:08.274) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(04:56:08.274) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 3.203281ms
D/(04:56:08.275) KurobaEx | SiteManager: SuspendableInitializer initWithValue() called
D/(04:56:08.275) KurobaEx | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.275) KurobaEx | SiteManager: SuspendableInitializer initWithValue() done
D/(04:56:08.275) KurobaEx | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(04:56:08.275) KurobaEx | SiteManager: loadSitesInternal() end, took 36.065990ms
D/(04:56:08.275) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(04:56:08.282) KurobaEx | BoardRepository: loadAllBoards() -> 78 took 4.187084ms
D/(04:56:08.283) KurobaEx | BoardManager: SuspendableInitializer initWithValue() called
D/(04:56:08.283) KurobaEx | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(04:56:08.283) KurobaEx | BoardManager: SuspendableInitializer initWithValue() done
D/(04:56:08.284) KurobaEx | BoardManager: loadBoardsInternal() done. Loaded 78 boards
D/(04:56:08.284) KurobaEx | BoardManager: loadBoardsInternal() end, took 44.235365ms

```
Additional information
```
------------------------------
Android API Level: 31
App Version: v1.3.18
Phone Model: Xiaomi 2107113SG
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 00:00:02.689
System animations state: duration: 0.0, transition: 1.0, window: 1.0
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 12; 2107113SG Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx v1.3.18
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: null
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/c69894e02d03dfd47277e6fe9ba6b759ef7e40ae
