### ISSUE TITLE
java.lang.NullPointerException Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#566]
Stacktrace
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.github.k1rakishou.common.AndroidUtils.getProcessType(AndroidUtils.java:4)
	at com.github.k1rakishou.chan.core.watcher.BookmarkWatcherCoordinator$Companion.cancelBackgroundBookmarkWatching(BookmarkWatcherCoordinator.kt:5)
	at com.github.k1rakishou.chan.core.watcher.BookmarkWatcherCoordinator$onBookmarksChanged$2.invokeSuspend(BookmarkWatcherCoordinator.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

Logs
```
D/(08:24:23.144) KurobaEx-fdroid | ApplicationMigrationManager: performMigrationV1 begin
D/(08:24:23.182) KurobaEx-fdroid | ApplicationMigrationManager: performMigrationV1 end
D/(08:24:23.182) KurobaEx-fdroid | ApplicationMigrationManager: performMigrationV2 begin
D/(08:24:23.183) KurobaEx-fdroid | ApplicationMigrationManager: performMigrationV2 end
D/(08:24:23.184) KurobaEx-fdroid | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(08:24:23.199) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_dark.json) does not exist on the disk
D/(08:24:23.200) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_light.json) does not exist on the disk
D/(08:24:23.218) KurobaEx-fdroid | ChanPostRepository: ChanPostRepository.initialize()
D/(08:24:23.236) KurobaEx-fdroid | SiteManager: SiteManager.initialize()
D/(08:24:23.237) KurobaEx-fdroid | BoardManager: BoardManager.initialize()
D/(08:24:23.237) KurobaEx-fdroid | SiteManager: loadSitesInternal() start
D/(08:24:23.238) KurobaEx-fdroid | BoardManager: loadBoardsInternal() start
D/(08:24:23.238) KurobaEx-fdroid | BookmarksManager: BookmarksManager.initialize()
D/(08:24:23.238) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(08:24:23.238) KurobaEx-fdroid | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(08:24:23.238) KurobaEx-fdroid | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(08:24:23.239) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() start
D/(08:24:23.239) KurobaEx-fdroid | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(08:24:23.240) KurobaEx-fdroid | ArchivesManager: ArchivesManager.initialize()
D/(08:24:23.241) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() start
D/(08:24:23.241) KurobaEx-fdroid | ChanFilterManager: ChanFilterManager.initialize()
D/(08:24:23.242) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() start
D/(08:24:23.243) KurobaEx-fdroid | Chan: Application initialization took 896ms
D/(08:24:23.269) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(08:24:23.269) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() called
D/(08:24:23.269) KurobaEx-fdroid | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.269) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() done
D/(08:24:23.269) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(08:24:23.272) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() end, took 28.754066ms
D/(08:24:23.299) KurobaEx-fdroid | StartActivity: onCreate() start isFreshStart: true, initializing everything
D/(08:24:23.301) KurobaEx-fdroid | ChanPostRepository: deleteOldPostsIfNeeded database is empty
D/(08:24:23.307) KurobaEx-fdroid | BookmarksRepository: initialize() -> 0 took 2.476199ms
D/(08:24:23.308) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() called
D/(08:24:23.309) KurobaEx-fdroid | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.309) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() done
D/(08:24:23.309) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() done. Loaded 0 bookmarks and 0 active bookmarks
D/(08:24:23.310) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() end, took 70.715580ms
D/(08:24:23.311) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(08:24:23.311) KurobaEx-fdroid | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.312) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(08:24:23.312) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(08:24:23.312) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() end, took 69.796674ms
D/(08:24:23.319) KurobaEx-fdroid | SiteRepository: initializeSites() -> 24 took 5.903386ms
D/(08:24:23.330) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(08:24:23.330) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(08:24:23.330) KurobaEx-fdroid | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.330) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(08:24:23.330) KurobaEx-fdroid | SiteRepository: allSitesLoadedInitializer initialized
D/(08:24:23.335) KurobaEx-fdroid | ChanPostRepository: deleteOldThreadsIfNeeded database is empty
D/(08:24:23.336) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(08:24:23.337) KurobaEx-fdroid | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.337) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(08:24:23.346) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(08:24:23.355) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://endchan.net/'
D/(08:24:23.405) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(08:24:23.421) KurobaEx-fdroid | Dvach: Using domain: 'https://2ch.hk/'
D/(08:24:23.433) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(08:24:23.434) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(ThreadSlideController)
D/(08:24:23.439) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(08:24:23.439) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.439) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(08:24:23.439) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(08:24:23.440) KurobaEx-fdroid | SiteManager: loadSitesInternal() end, took 202.238614ms
D/(08:24:23.440) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(08:24:23.444) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(08:24:23.451) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 0 took 2.512188ms
D/(08:24:23.455) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(08:24:23.455) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:23.456) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(08:24:23.456) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 0 boards
D/(08:24:23.456) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 218.512105ms
D/(08:24:23.457) KurobaEx-fdroid | ThreadLayout: ThreadLayout.create(threadControllerType=Catalog)
D/(08:24:23.622) KurobaEx-fdroid | CacheHandler: diskCacheDir=/data/user/0/com.github.k1rakishou.chan.fdroid/files/disk_cache, totalFileCacheDiskSize=268.4 MB
D/(08:24:23.624) KurobaEx-fdroid | InnerCache{0}: cacheFileType=ThreadDownloaderThumbnail, fileCacheDiskSize=13.4 MB
D/(08:24:23.628) KurobaEx-fdroid | InnerCache{0}: recalculateSize() start
D/(08:24:23.629) KurobaEx-fdroid | InnerCache{1}: cacheFileType=BookmarkThumbnail, fileCacheDiskSize=13.4 MB
D/(08:24:23.629) KurobaEx-fdroid | InnerCache{0}: recalculateSize() end took 509.167us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.630) KurobaEx-fdroid | InnerCache{0}: clearChunksCacheDirInternal() start
D/(08:24:23.631) KurobaEx-fdroid | InnerCache{0}: clearChunksCacheDirInternal() end
D/(08:24:23.631) KurobaEx-fdroid | InnerCache{1}: recalculateSize() start
D/(08:24:23.632) KurobaEx-fdroid | InnerCache{1}: recalculateSize() end took 314.896us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.633) KurobaEx-fdroid | InnerCache{1}: clearChunksCacheDirInternal() start
D/(08:24:23.633) KurobaEx-fdroid | InnerCache{2}: cacheFileType=NavHistoryThumbnail, fileCacheDiskSize=13.4 MB
D/(08:24:23.633) KurobaEx-fdroid | InnerCache{1}: clearChunksCacheDirInternal() end
D/(08:24:23.635) KurobaEx-fdroid | InnerCache{2}: recalculateSize() start
D/(08:24:23.636) KurobaEx-fdroid | InnerCache{3}: cacheFileType=SiteIcon, fileCacheDiskSize=13.4 MB
D/(08:24:23.636) KurobaEx-fdroid | InnerCache{2}: recalculateSize() end took 294.062us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.637) KurobaEx-fdroid | InnerCache{2}: clearChunksCacheDirInternal() start
D/(08:24:23.638) KurobaEx-fdroid | InnerCache{2}: clearChunksCacheDirInternal() end
D/(08:24:23.639) KurobaEx-fdroid | InnerCache{3}: recalculateSize() start
D/(08:24:23.640) KurobaEx-fdroid | InnerCache{3}: recalculateSize() end took 227.865us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.640) KurobaEx-fdroid | InnerCache{4}: cacheFileType=PostMediaThumbnail, fileCacheDiskSize=13.4 MB
D/(08:24:23.640) KurobaEx-fdroid | InnerCache{3}: clearChunksCacheDirInternal() start
D/(08:24:23.641) KurobaEx-fdroid | InnerCache{3}: clearChunksCacheDirInternal() end
D/(08:24:23.642) KurobaEx-fdroid | InnerCache{4}: recalculateSize() start
D/(08:24:23.643) KurobaEx-fdroid | InnerCache{5}: cacheFileType=PostMediaFull, fileCacheDiskSize=174.5 MB
D/(08:24:23.643) KurobaEx-fdroid | InnerCache{4}: recalculateSize() end took 198.907us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.643) KurobaEx-fdroid | InnerCache{4}: clearChunksCacheDirInternal() start
D/(08:24:23.643) KurobaEx-fdroid | InnerCache{5}: recalculateSize() start
D/(08:24:23.644) KurobaEx-fdroid | InnerCache{4}: clearChunksCacheDirInternal() end
D/(08:24:23.644) KurobaEx-fdroid | InnerCache{5}: recalculateSize() end took 200.521us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.644) KurobaEx-fdroid | InnerCache{5}: clearChunksCacheDirInternal() start
D/(08:24:23.644) KurobaEx-fdroid | InnerCache{6}: cacheFileType=Other, fileCacheDiskSize=26.8 MB
D/(08:24:23.644) KurobaEx-fdroid | InnerCache{5}: clearChunksCacheDirInternal() end
D/(08:24:23.645) KurobaEx-fdroid | CacheHandler: CacheHandler.init() took 37.631619ms
D/(08:24:23.645) KurobaEx-fdroid | InnerCache{6}: recalculateSize() start
D/(08:24:23.645) KurobaEx-fdroid | InnerCache{6}: recalculateSize() end took 281.094us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(08:24:23.646) KurobaEx-fdroid | InnerCache{6}: clearChunksCacheDirInternal() start
D/(08:24:23.646) KurobaEx-fdroid | InnerCache{6}: clearChunksCacheDirInternal() end
D/(08:24:23.662) KurobaEx-fdroid | NavigationControllerContainerLayout: initBrowseControllerTracker()
D/(08:24:23.666) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(08:24:23.671) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedTo(BrowseController)
D/(08:24:23.673) KurobaEx-fdroid | StartActivity: createUi took 362.433786ms
D/(08:24:23.677) KurobaEx-fdroid | UpdateManager: autoUpdateCheck()
D/(08:24:23.677) KurobaEx-fdroid | UpdateManager: Updater is disabled for fdroid builds!
D/(08:24:23.678) KurobaEx-fdroid | StartActivity: initializeDependencies took 1.156875ms
D/(08:24:23.678) KurobaEx-fdroid | StartActivityStartupHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: true)
D/(08:24:23.679) KurobaEx-fdroid | StartActivityStartupHandlerHelper: onNewIntentInternal() -> false
D/(08:24:23.679) KurobaEx-fdroid | StartActivityStartupHandlerHelper: restoreFresh()
D/(08:24:23.679) KurobaEx-fdroid | StartActivityStartupHandlerHelper: restoreFresh() Sites are not setup, showSitesNotSetup()
D/(08:24:23.694) KurobaEx-fdroid | StartActivity: onCreate() end isFreshStart: true
D/(08:24:23.696) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(08:24:23.697) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 76.771us, callbacks count: 4
D/(08:24:23.697) KurobaEx-fdroid | StartActivity: start
D/(08:24:23.882) KurobaEx-fdroid | BottomMenuPanel: updatePaddings() state=NotInitialized
D/(08:24:23.883) KurobaEx-fdroid | BottomMenuPanel: updatePaddings() state=Hidden, visibility: 0, translationY=76.0
D/(08:24:24.054) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(08:24:24.117) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(08:24:24.119) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithValue() called
D/(08:24:24.119) KurobaEx-fdroid | viewModelInitialized: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:24.120) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithValue() done
D/(08:24:24.122) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(0)
D/(08:24:24.124) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(08:24:24.124) KurobaEx-fdroid | BookmarksRepository: persist(0) took 2.568854ms
D/(08:24:24.505) KurobaEx-fdroid | BookmarksManager: subscriptions=3
D/(08:24:24.505) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(08:24:24.525) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(08:24:24.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() no active bookmarks, nothing to do
D/(08:24:24.532) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(08:24:24.532) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 0 took 2.910313ms
E/(08:24:24.534) KurobaEx-fdroid | Chan: Coroutine undeliverable exception
E/(08:24:24.534) KurobaEx-fdroid | Chan: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.common.AndroidUtils.getProcessType(AndroidUtils.java:4)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.core.watcher.BookmarkWatcherCoordinator$Companion.cancelBackgroundBookmarkWatching(BookmarkWatcherCoordinator.kt:5)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.core.watcher.BookmarkWatcherCoordinator$onBookmarksChanged$2.invokeSuspend(BookmarkWatcherCoordinator.kt:15)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at android.os.Looper.loop(Looper.java:223)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/(08:24:24.534) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/(08:24:24.547) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(08:24:24.547) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 21.076043ms
D/(08:24:25.287) KurobaEx-fdroid | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(08:24:25.315) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_dark.json) does not exist on the disk
D/(08:24:25.315) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_light.json) does not exist on the disk
D/(08:24:25.324) KurobaEx-fdroid | ChanPostRepository: ChanPostRepository.initialize()
D/(08:24:25.337) KurobaEx-fdroid | SiteManager: SiteManager.initialize()
D/(08:24:25.338) KurobaEx-fdroid | BoardManager: BoardManager.initialize()
D/(08:24:25.339) KurobaEx-fdroid | BookmarksManager: BookmarksManager.initialize()
D/(08:24:25.340) KurobaEx-fdroid | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(08:24:25.340) KurobaEx-fdroid | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(08:24:25.340) KurobaEx-fdroid | SiteManager: loadSitesInternal() start
D/(08:24:25.341) KurobaEx-fdroid | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(08:24:25.342) KurobaEx-fdroid | ArchivesManager: ArchivesManager.initialize()
D/(08:24:25.342) KurobaEx-fdroid | ChanFilterManager: ChanFilterManager.initialize()
D/(08:24:25.342) KurobaEx-fdroid | BoardManager: loadBoardsInternal() start
D/(08:24:25.343) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(08:24:25.343) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() start
D/(08:24:25.343) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() start
D/(08:24:25.344) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() start
D/(08:24:25.345) KurobaEx-fdroid | Chan: Application initialization took 660ms
D/(08:24:25.360) KurobaEx-fdroid | ChanPostRepository: deleteOldPostsIfNeeded database is empty
D/(08:24:25.365) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(08:24:25.365) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() called
D/(08:24:25.365) KurobaEx-fdroid | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.365) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() done
D/(08:24:25.366) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(08:24:25.370) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() end, took 22.741043ms
D/(08:24:25.374) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(08:24:25.374) KurobaEx-fdroid | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.374) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(08:24:25.374) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(08:24:25.374) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() end, took 29.695471ms
D/(08:24:25.378) KurobaEx-fdroid | BookmarksRepository: initialize() -> 0 took 2.615781ms
D/(08:24:25.386) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() called
D/(08:24:25.387) KurobaEx-fdroid | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.387) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() done
D/(08:24:25.387) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() done. Loaded 0 bookmarks and 0 active bookmarks
D/(08:24:25.388) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() end, took 44.378598ms
D/(08:24:25.390) KurobaEx-fdroid | ChanPostRepository: deleteOldThreadsIfNeeded database is empty
D/(08:24:25.392) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(08:24:25.392) KurobaEx-fdroid | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.392) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(08:24:25.393) KurobaEx-fdroid | CrashReportActivity: CrashReportActivity launched
E/(08:24:25.405) KurobaEx-fdroid | CrashReportActivity: Got new exception: java.lang.NullPointerException
D/(08:24:25.410) KurobaEx-fdroid | SiteRepository: initializeSites() -> 24 took 11.898595ms
D/(08:24:25.411) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(08:24:25.411) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(08:24:25.412) KurobaEx-fdroid | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.412) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(08:24:25.412) KurobaEx-fdroid | SiteRepository: allSitesLoadedInitializer initialized
D/(08:24:25.419) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(08:24:25.419) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 40.209us, callbacks count: 2
D/(08:24:25.421) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(08:24:25.426) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://endchan.net/'
D/(08:24:25.446) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(08:24:25.451) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(0)
D/(08:24:25.452) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(08:24:25.453) KurobaEx-fdroid | BookmarksRepository: persist(0) took 2.254792ms
D/(08:24:25.483) KurobaEx-fdroid | Dvach: Using domain: 'https://2ch.hk/'
D/(08:24:25.494) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(08:24:25.494) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(08:24:25.494) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.494) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(08:24:25.494) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 24 sites
D/(08:24:25.495) KurobaEx-fdroid | SiteManager: loadSitesInternal() end, took 153.805068ms
D/(08:24:25.498) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 0 took 1.107188ms
D/(08:24:25.499) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(08:24:25.499) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(08:24:25.500) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(08:24:25.500) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 0 boards
D/(08:24:25.500) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 157.289755ms
D/(08:24:25.857) KurobaEx-fdroid | BookmarksManager: subscriptions=2
D/(08:24:25.858) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(08:24:25.913) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(08:24:25.917) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() no active bookmarks, nothing to do
D/(08:24:25.917) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(08:24:25.948) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 1 took 22.390419ms
D/(08:24:25.950) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(08:24:25.950) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 37.419483ms

```
Additional information
```
------------------------------
Android API Level: 30
App Version: v1.3.18
Phone Model: motorola moto g(7) play
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 192
App running time: 00:00:04.939
System animations state: duration: 1.0, transition: 1.5, window: 1.5
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 11; moto g(7) play Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.18
maxPostsCountInPostsCache: 9830
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: null
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment]
Already fixed in v1.3.19
