### ISSUE TITLE
java.lang.RuntimeException Unable to destroy activity {com.github.k1rakishou.kurobaexlite/com.github.k1rakishou.kurobaexlite.ui.activity.MainActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#739]
Stacktrace
```
java.lang.RuntimeException: Unable to destroy activity {com.github.k1rakishou.kurobaexlite/com.github.k1rakishou.kurobaexlite.ui.activity.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5110)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:200)
	at android.os.Looper.loop(Looper.java:286)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException
	at androidx.compose.ui.focus.FocusRequesterModifierLocal.findFocusNode(FocusRequesterModifier.kt:17)
	at androidx.compose.ui.focus.FocusRequester.freeFocus(FocusRequester.kt:7)
	at com.github.k1rakishou.kurobaexlite.features.reply.ReplyInputWithButtonsKt$ReplyInput$1$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:2)
	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
	at androidx.compose.ui.platform.WrappedComposition.dispose(Wrapper.android.kt:5)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:2)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:27)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:7)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:10)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:1)
	at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1498)
	at android.app.Activity.performDestroy(Activity.java:8235)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1356)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5095)
	... 12 more

```

Logs
```
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^
D/KurobaExLite | ThreadAutoUpdater: Thread auto-updater resumed, threadDescriptor=ThreadDescriptor(4chan/co/133256982)
D/KurobaExLite | ThreadAutoUpdater: stopAutoUpdaterLoop() currentThreadDescriptor=ThreadDescriptor(4chan/co/133256982)
D/KurobaExLite | ThreadAutoUpdater: runAutoUpdaterLoop() start threadDescriptor=ThreadDescriptor(4chan/co/133256982)
D/KurobaExLite | BookmarkBackgroundWatcherWorker: doWork() start
D/KurobaExLite | FetchThreadBookmarkInfo: bookmarkDescriptorsCount=1
D/KurobaExLite | FetchThreadBookmarkInfo: fetchThreadBookmarkInfo stats: total results=1, errorsCount=0, alreadyDeletedCount=0, notFoundOnServerCount=0, badStatusCount=0, successCount=1
D/KurobaExLite | PersistBookmarks: persisting 1 bookmarks
D/KurobaExLite | CatalogPagesRepository: loading catalog page info for CatalogDescriptor(4chan/co)
D/KurobaExLite | FetchThreadBookmarkInfo: processResultsInternal() success, activeBookmarksCount: 0, took: 34.056670ms
D/KurobaExLite | BookmarkBackgroundWatcherWorker: fetchThreadBookmarkInfo() success
D/KurobaExLite | BookmarkBackgroundWatcherWorker: activeBookmarksCount: 0 the work loop is finished
D/KurobaExLite | BookmarkBackgroundWatcherWorker: doWork() end
D/KurobaExLite | CatalogPagesRepository: loaded 150 threads with page info for CatalogDescriptor(4chan/co)
D/KurobaExLite | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() appSettings.replyNotifications == false
D/KurobaExLite | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() appSettings.replyNotifications == false
D/KurobaExLite | PostScreenViewModel: restoreScrollPosition(CatalogDescriptor(4chan/co), null) lastRememberedPosition: LazyColumnRememberedPosition(orientation=1, index=138, offset=-780)
D/KurobaExLite | ApplicationVisibilityManager: vvv App went background vvv
D/KurobaExLite | ThreadAutoUpdater: Thread auto-updater paused, currentThreadDescriptor=ThreadDescriptor(4chan/co/133256982)
E/KurobaExLite | KurobaExLiteApplication: Unhandled exception in thread: main, error: java.lang.RuntimeException: Unable to destroy activity {com.github.k1rakishou.kurobaexlite/com.github.k1rakishou.kurobaexlite.ui.activity.MainActivity}: java.lang.NullPointerException
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5110)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
E/KurobaExLite | KurobaExLiteApplication: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/KurobaExLite | KurobaExLiteApplication: 	at android.os.Looper.loopOnce(Looper.java:200)
E/KurobaExLite | KurobaExLiteApplication: 	at android.os.Looper.loop(Looper.java:286)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.ActivityThread.main(ActivityThread.java:7666)
E/KurobaExLite | KurobaExLiteApplication: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaExLite | KurobaExLiteApplication: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/KurobaExLite | KurobaExLiteApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/KurobaExLite | KurobaExLiteApplication: Caused by: java.lang.NullPointerException
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.focus.FocusRequesterModifierLocal.findFocusNode(FocusRequesterModifier.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.focus.FocusRequester.freeFocus(FocusRequester.kt:7)
E/KurobaExLite | KurobaExLiteApplication: 	at com.github.k1rakishou.kurobaexlite.features.reply.ReplyInputWithButtonsKt$ReplyInput$1$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:2)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:8)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:6)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:17)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.platform.WrappedComposition.dispose(Wrapper.android.kt:5)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:2)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:27)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:7)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:10)
E/KurobaExLite | KurobaExLiteApplication: 	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:1)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1498)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.Activity.performDestroy(Activity.java:8235)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1356)
E/KurobaExLite | KurobaExLiteApplication: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5095)
E/KurobaExLite | KurobaExLiteApplication: 	... 12 more
D/KurobaExLite | CrashReportActivity: Got new exception: java.lang.RuntimeException
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^

```
Additional information
```
Android API Level: 30
App Version: 1.0.5
Phone Model: Xiaomi M2102J20SI
Flavor type: Production
isSlowDevice: false
MemoryClass: 256
App running time: 00:00:03.191
System animations info: duration: 0.0, transition: 1.0, window: 1.0

```

**Comment by K1rakishou** [comment]
Should be fixed by https://github.com/K1rakishou/KurobaExLite/commit/b2e9348eda8ebf0959c81f747d3a8f281bc84b42
