### ISSUE TITLE
java.lang.IndexOutOfBoundsException setSpan (-1 ... -1) starts before 0

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#781]
Stacktrace
```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1330)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:4)
	at android.text.Selection.setSelection(Selection.java:96)
	at android.text.Selection.setSelection(Selection.java:78)
	at android.widget.Editor$SelectionStartHandleView.updateSelection(Editor.java:7712)
	at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:6937)
	at android.widget.Editor$HandleView.updatePosition(Editor.java:6971)
	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:3701)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3325)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
	at android.view.Choreographer.doCallbacks(Choreographer.java:799)
	at android.view.Choreographer.doFrame(Choreographer.java:734)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```

Logs
```
D/(18:08:17.904) KurobaEx | ChanTicker: startOrRestartTickerInternal run action begin
D/(18:08:17.905) KurobaEx | ThreadPresenter: onChanTickerTick(TD{4chan/mlp/39128615})
D/(18:08:17.905) KurobaEx | ThreadPresenter: normalLoad() start
D/(18:08:17.905) KurobaEx | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/mlp/39128615}
D/(18:08:17.905) KurobaEx | ThreadPresenter: showLoading=false
D/(18:08:17.905) KurobaEx | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(18:08:17.905) KurobaEx | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(18:08:17.905) KurobaEx | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(18:08:17.905) KurobaEx | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(18:08:17.905) KurobaEx | ChanTicker: startOrRestartTickerInternal run action end
D/(18:08:17.905) KurobaEx | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=4, nextWaitTimeSeconds=60
D/(18:08:17.905) KurobaEx | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/mlp/39128615}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(18:08:17.905) KurobaEx | ChanThreadManager: loadInternal() Requested thread /TD{4chan/mlp/39128615}/
D/(18:08:17.905) KurobaEx | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/mlp/39128615}) begin
D/(18:08:17.905) KurobaEx | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/mlp/39128615})
D/(18:08:17.905) KurobaEx | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/mlp/39128615}) end, took 319.769us
D/(18:08:17.905) KurobaEx | ChanThreadManager: loadInternal(), chanDescriptor=TD{4chan/mlp/39128615} preloadThreadInfo took 382.153us
D/(18:08:17.905) KurobaEx | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/mlp/39128615}, UpdateCache) -> true
D/(18:08:17.905) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/mlp/thread/39128615.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{4chan/mlp/39128615}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader, postProcessFlags=null)
D/(18:08:17.905) KurobaEx | BookmarkForegroundWatcher: updateBookmarkForOpenedThread(TD{4chan/mlp/39128615}) called
D/(18:08:17.906) KurobaEx | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=TD{4chan/mlp/39128615})
D/(18:08:17.906) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Stable
D/(18:08:17.924) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() enqueued work with tag BookmarkWatcherController_Stable, backgroundIntervalMillis=900000
D/(18:08:17.924) KurobaEx | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...
D/(18:08:17.924) KurobaEx | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...done
D/(18:08:17.924) KurobaEx | BookmarkWatcherDelegate: doWorkInternal() updating 1 bookmarks
D/(18:08:17.925) KurobaEx | LastPageNotificationsHelper: showOrUpdateNotifications(1)
D/(18:08:17.925) KurobaEx | LastPageNotificationsHelper: Skipping notification for currently opened thread (TD{4chan/mlp/39128615})
D/(18:08:17.925) KurobaEx | LastPageNotificationsHelper: No threads to notify about last page
D/(18:08:17.925) KurobaEx | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() called, isCalledFromForeground=true, currentThreadDescriptor=TD{4chan/mlp/39128615}
D/(18:08:17.925) KurobaEx | FetchThreadBookmarkInfoUseCase: FetchThreadBookmarkInfoUseCase.execute(1)
D/(18:08:18.257) KurobaEx | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=TD{4chan/mlp/39128615})
D/(18:08:18.279) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/mlp/thread/39128615.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{4chan/mlp/39128615}, toParse=1, closed=false, deleted=false, archived=false, error=null}
D/(18:08:18.279) KurobaEx | NormalPostLoader: persistPosts(TD{4chan/mlp/39128615}, ChanReaderProcessor{chanDescriptor=TD{4chan/mlp/39128615}, toParse=1, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(18:08:18.283) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/mlp/39128615}) -> parsedPosts=1
D/(18:08:18.283) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/mlp/39128615}, postsToParseSize=1), internalIds=304, filters=0
D/(18:08:18.284) KurobaEx | ChanPostRepository: insertOrUpdateThreadPosts() 1 posts differ from the cache (total posts=1)
D/(18:08:18.285) KurobaEx | ChanThread: Thread cache (TD{4chan/mlp/39128615}) Added 0 new posts, updated 1 posts, marked as deleted 0 posts. sortAndRecalculationDuration=380us
D/(18:08:18.285) KurobaEx | ChanPostRepository: insertOrUpdateMany(TD{4chan/mlp/39128615}) -> 1
D/(18:08:18.289) KurobaEx | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=TD{4chan/mlp/39128615}, postsToParseCount=1)
D/(18:08:18.289) KurobaEx | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=TD{4chan/mlp/39128615}, filtersCount=0)
D/(18:08:18.290) KurobaEx | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{4chan/mlp/39128615}, postsCount=1)
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/mlp/thread/39128615.json.
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Network request execution took 345.430538ms.
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Json reading took 27.650539ms.
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Store new posts took 2.103307ms (stored 1 posts).
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Parse posts took 3.306769ms (parsed 1 out of 304 posts).
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Filter processing took 4.693us (filers count: 0).
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 987/13107.
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Current thread cached posts count: 304
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Threads with more than one post count: (4/8), total cached threads count: 149.
D/(18:08:18.290) KurobaEx | ChanThreadLoaderCoordinator: Total local processing time: 33.065308ms
D/(18:08:18.290) KurobaEx | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/mlp/39128615}) begin
D/(18:08:18.290) KurobaEx | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/mlp/39128615}) end
D/(18:08:18.290) KurobaEx | ChanThreadManager: loadThreadOrCatalog(), descriptor=TD{4chan/mlp/39128615} postloadThreadInfo took 71.154us
D/(18:08:18.290) KurobaEx | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/mlp/39128615}} (currentChanDescriptor=TD{4chan/mlp/39128615})
D/(18:08:18.290) KurobaEx | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/mlp/39128615}
D/(18:08:18.290) KurobaEx | ChanTicker: kickTicker(false)
D/(18:08:18.290) KurobaEx | KotlinExts: awaitUntilGloballyLaidOut(com.github.k1rakishou.chan.ui.view.LoadView{7ff55d3 V.E...... ........ 0,0-1080,2340 #7f0a0204 app:id/loadview}) widthOk=true, width=1080, heightOk=true, height=2340
D/(18:08:18.291) KurobaEx | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/mlp/39128615}
D/(18:08:18.291) KurobaEx | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/mlp/39128615}, waiting 60000ms
D/(18:08:18.292) KurobaEx | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/mlp/39128615}, postHidesCount=0, postFiltersCount=0)
D/(18:08:18.292) KurobaEx | PostHideHelper: processPostFilters(TD{4chan/mlp/39128615}) start
D/(18:08:18.294) KurobaEx | PostHideHelper: processPostFilters(TD{4chan/mlp/39128615}) end (hiddenPostsCount=0, removedPostsCount=0, normalPostsCount=304, total=304)
D/(18:08:18.295) KurobaEx | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/mlp/39128615})
D/(18:08:18.295) KurobaEx | ThreadCellData: runPreloading() start
D/(18:08:18.296) KurobaEx | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=304
D/(18:08:18.296) KurobaEx | ThreadCellData: runPreloading() startingPosition=298, dataListSize=304
D/(18:08:18.296) KurobaEx | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/mlp/39128615}) -> true applyFilterDuration=2.755769ms, setThreadPostsDuration=1.254769ms, totalDuration=5.318769ms
D/(18:08:18.296) KurobaEx | ThreadPresenter: onChanLoaderData(TD{4chan/mlp/39128615}) end, took 5.768230ms
D/(18:08:18.296) KurobaEx | ThreadPresenter: normalLoad() end
D/(18:08:18.301) KurobaEx | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/mlp/39128615})
D/(18:08:18.301) KurobaEx | HistoryNavigationManager: persistNavigationStack async called
D/(18:08:18.302) KurobaEx | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=257
D/(18:08:18.302) KurobaEx | NavHistoryLocalSource: persist(navHistoryStack.size=257)
D/(18:08:18.302) KurobaEx | BookmarkWatcherDelegate: fetchThreadBookmarkInfo stats: total results=1, errorsCount=0, alreadyDeletedCount=0, notFoundOnServerCount=0, badStatusCount=0, successCount=1
D/(18:08:18.329) KurobaEx | HistoryNavigationRepository: persist(257) took 27.254154ms
D/(18:08:18.333) KurobaEx | HistoryNavigationManager: persistNavigationStack async finished
D/(18:08:18.333) KurobaEx | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() success, activeBookmarksCount=5
D/(18:08:18.333) KurobaEx | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() took 408.423384ms
D/(18:08:18.334) KurobaEx | ThreadCellData: runPreloading() end, took 38.121846ms
E/(18:08:20.328) KurobaEx | Chan: Unhandled exception in thread: main
E/(18:08:20.328) KurobaEx | Chan: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
E/(18:08:20.328) KurobaEx | Chan: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1330)
E/(18:08:20.328) KurobaEx | Chan: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
E/(18:08:20.328) KurobaEx | Chan: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
E/(18:08:20.328) KurobaEx | Chan: 	at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:4)
E/(18:08:20.328) KurobaEx | Chan: 	at android.text.Selection.setSelection(Selection.java:96)
E/(18:08:20.328) KurobaEx | Chan: 	at android.text.Selection.setSelection(Selection.java:78)
E/(18:08:20.328) KurobaEx | Chan: 	at android.widget.Editor$SelectionStartHandleView.updateSelection(Editor.java:7712)
E/(18:08:20.328) KurobaEx | Chan: 	at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:6937)
E/(18:08:20.328) KurobaEx | Chan: 	at android.widget.Editor$HandleView.updatePosition(Editor.java:6971)
E/(18:08:20.328) KurobaEx | Chan: 	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:3701)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3325)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.Choreographer.doCallbacks(Choreographer.java:799)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.Choreographer.doFrame(Choreographer.java:734)
E/(18:08:20.328) KurobaEx | Chan: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
E/(18:08:20.328) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(18:08:20.328) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(18:08:20.328) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:236)
E/(18:08:20.328) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/(18:08:20.328) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(18:08:20.328) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/(18:08:20.328) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
D/(18:08:20.592) KurobaEx | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(18:08:20.608) KurobaEx | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan/files/kurobaex_theme_light.json) does not exist on the disk
D/(18:08:20.609) KurobaEx | ChanPostRepository: ChanPostRepository.initialize()
D/(18:08:20.611) KurobaEx | SiteManager: SiteManager.initialize()
D/(18:08:20.611) KurobaEx | BoardManager: BoardManager.initialize()
D/(18:08:20.611) KurobaEx | SiteManager: loadSitesInternal() start
D/(18:08:20.612) KurobaEx | BookmarksManager: BookmarksManager.initialize()
D/(18:08:20.612) KurobaEx | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(18:08:20.612) KurobaEx | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(18:08:20.612) KurobaEx | BoardManager: loadBoardsInternal() start
D/(18:08:20.612) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(18:08:20.612) KurobaEx | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(18:08:20.612) KurobaEx | BookmarksManager: initializeBookmarksInternal() start
D/(18:08:20.612) KurobaEx | ArchivesManager: ArchivesManager.initialize()
D/(18:08:20.613) KurobaEx | ChanFilterManager: ChanFilterManager.initialize()
D/(18:08:20.613) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() start
D/(18:08:20.613) KurobaEx | ChanFilterManager: loadFiltersInternal() start
D/(18:08:20.613) KurobaEx | Chan: Application initialization took 154ms
D/(18:08:20.617) KurobaEx | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(18:08:20.617) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() called
D/(18:08:20.617) KurobaEx | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.617) KurobaEx | ArchivesManager: SuspendableInitializer initWithValue() done
D/(18:08:20.617) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(18:08:20.618) KurobaEx | ArchivesManager: initializeArchivesManagerInternal() end, took 4.692923ms
D/(18:08:20.621) KurobaEx | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 19458, max allowed posts amount: 75000
D/(18:08:20.626) KurobaEx | BookmarksRepository: initialize() -> 5 took 3.404ms
D/(18:08:20.627) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() called
D/(18:08:20.627) KurobaEx | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.627) KurobaEx | BookmarksManager: SuspendableInitializer initWithValue() done
D/(18:08:20.627) KurobaEx | BookmarksManager: initializeBookmarksInternal() done. Loaded 5 bookmarks and 5 active bookmarks
D/(18:08:20.627) KurobaEx | BookmarksManager: initializeBookmarksInternal() end, took 14.801616ms
D/(18:08:20.628) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(18:08:20.628) KurobaEx | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.628) KurobaEx | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(18:08:20.628) KurobaEx | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(18:08:20.628) KurobaEx | ChanFilterManager: loadFiltersInternal() end, took 15.431923ms
D/(18:08:20.631) KurobaEx | SiteRepository: initializeSites() -> 27 took 2.231692ms
D/(18:08:20.631) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(18:08:20.631) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(18:08:20.631) KurobaEx | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.631) KurobaEx | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(18:08:20.631) KurobaEx | SiteRepository: allSitesLoadedInitializer initialized
D/(18:08:20.632) KurobaEx | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 9875, max allowed threads amount: 12500
D/(18:08:20.633) KurobaEx | CrashReportActivity: CrashReportActivity launched
D/(18:08:20.633) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(18:08:20.633) KurobaEx | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.633) KurobaEx | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(18:08:20.634) KurobaEx | LynxchanSite: Using domain: 'https://yeshoney.xyz/'
D/(18:08:20.635) KurobaEx | LynxchanSite: Using domain: 'https://kohlchan.net/'
E/(18:08:20.639) KurobaEx | CrashReportActivity: Got new exception: java.lang.IndexOutOfBoundsException
D/(18:08:20.640) KurobaEx | LynxchanSite: Using domain: 'https://endchan.net/'
E/(18:08:20.640) KurobaEx | SiteManager: Unknown site descriptor: SD{yuki.la}
D/(18:08:20.644) KurobaEx | Chan: ^^^ App went foreground ^^^
D/(18:08:20.644) KurobaEx | ApplicationVisibilityManager: onEnteredForeground() callback execution took 45.462us, callbacks count: 2
E/(18:08:20.644) KurobaEx | SiteManager: Unknown site descriptor: SD{archive.rebeccablacktech.com}
D/(18:08:20.650) KurobaEx | Dvach: Using domain: 'https://2ch.hk/'
D/(18:08:20.655) KurobaEx | SiteManager: SuspendableInitializer initWithValue() called
D/(18:08:20.655) KurobaEx | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.655) KurobaEx | SiteManager: SuspendableInitializer initWithValue() done
D/(18:08:20.655) KurobaEx | SiteManager: siteRepository.initializeSites() done. Loaded 27 sites
D/(18:08:20.655) KurobaEx | SiteManager: loadSitesInternal() end, took 43.200616ms
D/(18:08:20.655) KurobaEx | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(18:08:20.658) KurobaEx | BoardRepository: loadAllBoards() -> 78 took 2.366539ms
D/(18:08:20.658) KurobaEx | BoardManager: SuspendableInitializer initWithValue() called
D/(18:08:20.659) KurobaEx | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:08:20.659) KurobaEx | BoardManager: SuspendableInitializer initWithValue() done
D/(18:08:20.659) KurobaEx | BoardManager: loadBoardsInternal() done. Loaded 78 boards
D/(18:08:20.659) KurobaEx | BoardManager: loadBoardsInternal() end, took 46.800923ms
D/(18:08:20.662) KurobaEx | BookmarksManager: persistBookmarks async called
D/(18:08:20.663) KurobaEx | ThreadBookmarkLocalSource: persist(5)
D/(18:08:20.664) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(18:08:20.664) KurobaEx | BookmarksRepository: persist(5) took 1.058846ms
D/(18:08:20.745) KurobaEx | BookmarksManager: subscriptions=2
D/(18:08:20.745) KurobaEx | BookmarksManager: persistBookmarks async finished
D/(18:08:20.751) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(18:08:20.753) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() calling startWatchingIfNotWatchingYet()
D/(18:08:20.753) KurobaEx | BookmarkForegroundWatcher: working == true, calling updateBookmarksWorkerLoop()
D/(18:08:20.754) KurobaEx | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=110ms)
D/(18:08:20.755) KurobaEx | ThreadBookmarkGroupRepository: initialize() -> 26 took 2.987462ms
D/(18:08:20.756) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 26 bookmark groups
D/(18:08:20.756) KurobaEx | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 4.285230ms
D/(18:08:21.755) KurobaEx | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=1111ms)
D/(18:08:22.755) KurobaEx | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=2111ms)
D/(18:08:23.756) KurobaEx | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=3112ms)

```
Additional information
```
------------------------------
Android API Level: 30
App Version: v1.3.21
Phone Model: Xiaomi Redmi Note 8 Pro
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 00:00:03.393
System animations state: duration: 1.0, transition: 1.0, window: 1.0
------------------------------
Current layout mode: PHONE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: true
useMpvVideoPlayer: true
userAgent: Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx v1.3.21
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 50
ImageSaver root directory: content://com.android.externalstorage.documents/tree/1B5F-162B%3Afiles%2Fdownload
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 30000
Watch foreground adaptive interval: false
Background watcher enabled: true
Watch background interval: 900000
Filter watch enabled: true
Filter watch interval: 43200000
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment]
Yeah, I don't think I can do anything here. It crashes inside of a onPreDraw callback inside of a private class PositionListener which is inside of a private class Editor. There are just no public methods for me to override to consume the crash.
