### ISSUE TITLE
java.lang.IllegalStateException Files not sorted! addedOn='1666456540587', prevAddedOn='1666456540587'

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#794]
Stacktrace
```
java.lang.IllegalStateException: Files not sorted! addedOn='1666456540587', prevAddedOn='1666456540587'
	at com.github.k1rakishou.chan.features.reply.data.ReplyFilesStorage.ensureFilesSorted(ReplyFilesStorage.kt:4)
	at com.github.k1rakishou.chan.features.reply.data.ReplyFilesStorage.addNewReplyFile(ReplyFilesStorage.kt:57)
	at com.github.k1rakishou.chan.core.manager.ReplyManager.addNewReplyFileIntoStorage(ReplyManager.kt:2)
	at com.github.k1rakishou.chan.ui.helper.picker.ImagePickHelper.pickFilesFromIncomingShare(ImagePickHelper.kt:41)
	at com.github.k1rakishou.chan.ui.helper.picker.ImagePickHelper$pickFilesFromIncomingShare$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f20e9c7, Dispatchers.Main.immediate]

```

Logs
```
D/(18:35:39.200) KurobaEx-fdroid | filesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(18:35:39.200) KurobaEx-fdroid | filesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:39.200) KurobaEx-fdroid | filesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(18:35:39.215) KurobaEx-fdroid | Dvach: Using domain: 'https://2ch.hk/'
D/(18:35:39.225) KurobaEx-fdroid | SharingActivity: onNewIntentInternal called, action=android.intent.action.SEND
D/(18:35:39.227) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(18:35:39.228) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(18:35:39.228) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:39.228) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(18:35:39.228) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 27 sites
D/(18:35:39.228) KurobaEx-fdroid | SiteManager: loadSitesInternal() end, took 373.315615ms
D/(18:35:39.378) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 1636 took 141.251153ms
D/(18:35:39.379) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(18:35:39.379) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:39.379) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(18:35:39.379) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 1636 boards
D/(18:35:39.379) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 524.475616ms
D/(18:35:39.537) KurobaEx-fdroid | StartActivity: onCreate() start isFreshStart: false, initializing everything
D/(18:35:39.621) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(18:35:39.643) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(18:35:39.644) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(ThreadSlideController)
D/(18:35:39.648) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(18:35:39.662) KurobaEx-fdroid | ThreadLayout: ThreadLayout.create(threadControllerType=Catalog)
D/(18:35:39.824) KurobaEx-fdroid | CacheHandler: diskCacheDir=/data/user/0/com.github.k1rakishou.chan.fdroid/files/disk_cache, totalFileCacheDiskSize=134,2 MB
D/(18:35:39.828) KurobaEx-fdroid | InnerCache{0}: cacheFileType=ThreadDownloaderThumbnail, fileCacheDiskSize=6,7 MB
D/(18:35:39.830) KurobaEx-fdroid | InnerCache{1}: cacheFileType=BookmarkThumbnail, fileCacheDiskSize=6,7 MB
D/(18:35:39.831) KurobaEx-fdroid | InnerCache{0}: recalculateSize() start
D/(18:35:39.832) KurobaEx-fdroid | InnerCache{0}: recalculateSize() end took 485.461us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(18:35:39.832) KurobaEx-fdroid | InnerCache{0}: clearChunksCacheDirInternal() start
D/(18:35:39.832) KurobaEx-fdroid | InnerCache{0}: clearChunksCacheDirInternal() end
D/(18:35:39.834) KurobaEx-fdroid | InnerCache{2}: cacheFileType=NavHistoryThumbnail, fileCacheDiskSize=6,7 MB
D/(18:35:39.835) KurobaEx-fdroid | InnerCache{1}: recalculateSize() start
D/(18:35:39.836) KurobaEx-fdroid | InnerCache{2}: recalculateSize() start
D/(18:35:39.838) KurobaEx-fdroid | InnerCache{3}: cacheFileType=SiteIcon, fileCacheDiskSize=6,7 MB
D/(18:35:39.841) KurobaEx-fdroid | InnerCache{4}: cacheFileType=PostMediaThumbnail, fileCacheDiskSize=6,7 MB
D/(18:35:39.842) KurobaEx-fdroid | InnerCache{3}: recalculateSize() start
D/(18:35:39.842) KurobaEx-fdroid | InnerCache{4}: recalculateSize() start
D/(18:35:39.844) KurobaEx-fdroid | InnerCache{5}: cacheFileType=PostMediaFull, fileCacheDiskSize=87,2 MB
D/(18:35:39.847) KurobaEx-fdroid | InnerCache{5}: recalculateSize() start
D/(18:35:39.852) KurobaEx-fdroid | InnerCache{6}: cacheFileType=Other, fileCacheDiskSize=13,4 MB
D/(18:35:39.853) KurobaEx-fdroid | CacheHandler: CacheHandler.init() took 48.933231ms
D/(18:35:39.855) KurobaEx-fdroid | InnerCache{6}: recalculateSize() start
D/(18:35:39.855) KurobaEx-fdroid | InnerCache{6}: recalculateSize() end took 191.308us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(18:35:39.855) KurobaEx-fdroid | InnerCache{6}: clearChunksCacheDirInternal() start
D/(18:35:39.855) KurobaEx-fdroid | InnerCache{6}: clearChunksCacheDirInternal() end
D/(18:35:39.867) KurobaEx-fdroid | NavigationControllerContainerLayout: initBrowseControllerTracker()
D/(18:35:39.868) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(18:35:39.870) KurobaEx-fdroid | InnerCache{5}: recalculateSize() end took 22.213538ms, filesOnDiskCount=58, fullyDownloadedFilesCount=0
D/(18:35:39.870) KurobaEx-fdroid | InnerCache{5}: clearChunksCacheDirInternal() start
D/(18:35:39.870) KurobaEx-fdroid | InnerCache{5}: clearChunksCacheDirInternal() end
D/(18:35:39.872) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedTo(BrowseController)
D/(18:35:39.873) KurobaEx-fdroid | StartActivity: createUi took 321.869ms
D/(18:35:39.874) KurobaEx-fdroid | UpdateManager: autoUpdateCheck()
D/(18:35:39.874) KurobaEx-fdroid | UpdateManager: Updater is disabled for fdroid builds!
D/(18:35:39.874) KurobaEx-fdroid | StartActivity: initializeDependencies took 406.231us
D/(18:35:39.874) KurobaEx-fdroid | StartActivityStartupHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: false)
D/(18:35:39.874) KurobaEx-fdroid | StartActivityStartupHandlerHelper: onNewIntentInternal() -> false
D/(18:35:39.875) KurobaEx-fdroid | StartActivityStartupHandlerHelper: restoreFromSavedState()
D/(18:35:39.875) KurobaEx-fdroid | BrowseController: setCatalog(CD{4chan/g})
D/(18:35:39.876) KurobaEx-fdroid | BrowseController: loadCatalog(CD{4chan/g})
D/(18:35:39.880) KurobaEx-fdroid | ThreadPresenter: bindChanDescriptor(chanDescriptor=CD{4chan/g})
D/(18:35:39.883) KurobaEx-fdroid | ThreadPresenter: chanThreadTicker.startTicker(CD{4chan/g})
D/(18:35:39.883) KurobaEx-fdroid | PageRequestManager: Requesting new board pages for /g/
D/(18:35:39.883) KurobaEx-fdroid | ChanTicker: startTicker(CD{4chan/g})
D/(18:35:39.883) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(18:35:39.883) KurobaEx-fdroid | ChanTicker: kickTicker() called with catalog descriptor, ticking right away
D/(18:35:39.901) KurobaEx-fdroid | BrowseController: showThread(TD{4chan/g/89362012}, ShowThreadOptions(switchToThreadController=true, pushControllerWithAnimation=false))
D/(18:35:39.903) KurobaEx-fdroid | ThreadLayout: ThreadLayout.create(threadControllerType=Thread)
D/(18:35:39.917) KurobaEx-fdroid | ProxyStorage: loadProxies()
D/(18:35:39.931) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:39.932) KurobaEx-fdroid | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: true
D/(18:35:39.953) KurobaEx-fdroid | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(18:35:39.961) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedFrom(BrowseController)
D/(18:35:39.962) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedTo(ViewThreadController)
D/(18:35:39.964) KurobaEx-fdroid | StartActivity: onCreate() end isFreshStart: false
D/(18:35:39.966) KurobaEx-fdroid | StartActivity: start
D/(18:35:40.011) KurobaEx-fdroid | InnerCache{3}: recalculateSize() end took 168.876846ms, filesOnDiskCount=153, fullyDownloadedFilesCount=0
D/(18:35:40.011) KurobaEx-fdroid | InnerCache{3}: clearChunksCacheDirInternal() start
D/(18:35:40.011) KurobaEx-fdroid | InnerCache{3}: clearChunksCacheDirInternal() end
D/(18:35:40.399) KurobaEx-fdroid | BottomMenuPanel: updatePaddings() state=NotInitialized
D/(18:35:40.400) KurobaEx-fdroid | BottomMenuPanel: updatePaddings() state=Hidden, visibility: 0, translationY=226.0
D/(18:35:40.427) KurobaEx-fdroid | InnerCache{1}: recalculateSize() end took 591.572307ms, filesOnDiskCount=696, fullyDownloadedFilesCount=0
D/(18:35:40.427) KurobaEx-fdroid | InnerCache{1}: clearChunksCacheDirInternal() start
D/(18:35:40.439) KurobaEx-fdroid | InnerCache{1}: clearChunksCacheDirInternal() end
D/(18:35:40.509) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(18:35:40.585) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(18:35:40.587) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(26)
D/(18:35:40.589) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(18:35:40.589) KurobaEx-fdroid | BookmarksRepository: persist(26) took 2.247385ms
D/(18:35:40.723) KurobaEx-fdroid | JsonReaderRequest: Request "Chan4PagesRequest" to "https://a.4cdn.org/g/threads.json" took 834.678693ms
D/(18:35:40.740) KurobaEx-fdroid | PageRequestManager: Got pages for 4chan/g/
D/(18:35:40.754) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithValue() called
D/(18:35:40.754) KurobaEx-fdroid | viewModelInitialized: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:40.754) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithValue() done
D/(18:35:40.758) KurobaEx-fdroid | ChanTicker: StopTicker
D/(18:35:40.760) KurobaEx-fdroid | ViewThreadController: loadThread(TD{4chan/g/89362012})
D/(18:35:40.761) KurobaEx-fdroid | ThreadPresenter: bindChanDescriptor(chanDescriptor=TD{4chan/g/89362012})
D/(18:35:40.762) KurobaEx-fdroid | ThreadPresenter: chanThreadTicker.startTicker(TD{4chan/g/89362012})
D/(18:35:40.762) KurobaEx-fdroid | ChanTicker: startTicker(TD{4chan/g/89362012})
D/(18:35:40.762) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(18:35:40.762) KurobaEx-fdroid | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/g/89362012}
D/(18:35:40.762) KurobaEx-fdroid | ThreadDownloadManager: initializeThreadDownloadManagerInternal() start
D/(18:35:40.769) KurobaEx-fdroid | ThreadDownloadManager: initializeThreadDownloadManagerInternal() end, took 6.447693ms
D/(18:35:40.783) KurobaEx-fdroid | BookmarksManager: subscriptions=2
D/(18:35:40.783) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
E/(18:35:40.807) KurobaEx-fdroid | Chan: Unhandled exception in thread: main
E/(18:35:40.807) KurobaEx-fdroid | Chan: java.lang.IllegalStateException: Files not sorted! addedOn='1666456540587', prevAddedOn='1666456540587'
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.reply.data.ReplyFilesStorage.ensureFilesSorted(ReplyFilesStorage.kt:4)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.reply.data.ReplyFilesStorage.addNewReplyFile(ReplyFilesStorage.kt:57)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.core.manager.ReplyManager.addNewReplyFileIntoStorage(ReplyManager.kt:2)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.ui.helper.picker.ImagePickHelper.pickFilesFromIncomingShare(ImagePickHelper.kt:41)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.ui.helper.picker.ImagePickHelper$pickFilesFromIncomingShare$1.invokeSuspend(Unknown Source:12)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at android.os.Looper.loopOnce(Looper.java:226)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at android.os.Looper.loop(Looper.java:313)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/(18:35:40.807) KurobaEx-fdroid | Chan: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f20e9c7, Dispatchers.Main.immediate]
D/(18:35:40.905) KurobaEx-fdroid | InnerCache{2}: recalculateSize() end took 1.069024308s, filesOnDiskCount=810, fullyDownloadedFilesCount=0
D/(18:35:40.906) KurobaEx-fdroid | InnerCache{2}: clearChunksCacheDirInternal() start
D/(18:35:40.906) KurobaEx-fdroid | InnerCache{2}: clearChunksCacheDirInternal() end
D/(18:35:40.945) KurobaEx-fdroid | InnerCache{4}: recalculateSize() end took 1.102111692s, filesOnDiskCount=1549, fullyDownloadedFilesCount=0
D/(18:35:40.945) KurobaEx-fdroid | InnerCache{4}: clearChunksCacheDirInternal() start
D/(18:35:40.945) KurobaEx-fdroid | InnerCache{4}: clearChunksCacheDirInternal() end
D/(18:35:43.405) KurobaEx-fdroid | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(18:35:43.563) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_dark.json) does not exist on the disk
D/(18:35:43.563) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_light.json) does not exist on the disk
D/(18:35:43.567) KurobaEx-fdroid | ChanPostRepository: ChanPostRepository.initialize()
D/(18:35:43.576) KurobaEx-fdroid | SiteManager: SiteManager.initialize()
D/(18:35:43.577) KurobaEx-fdroid | BoardManager: BoardManager.initialize()
D/(18:35:43.577) KurobaEx-fdroid | BookmarksManager: BookmarksManager.initialize()
D/(18:35:43.578) KurobaEx-fdroid | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(18:35:43.579) KurobaEx-fdroid | SiteManager: loadSitesInternal() start
D/(18:35:43.578) KurobaEx-fdroid | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(18:35:43.580) KurobaEx-fdroid | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(18:35:43.583) KurobaEx-fdroid | ArchivesManager: ArchivesManager.initialize()
D/(18:35:43.584) KurobaEx-fdroid | ChanFilterManager: ChanFilterManager.initialize()
D/(18:35:43.586) KurobaEx-fdroid | Chan: Application initialization took 962ms
D/(18:35:43.591) KurobaEx-fdroid | BoardManager: loadBoardsInternal() start
D/(18:35:43.592) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(18:35:43.592) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() start
D/(18:35:43.614) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() start
D/(18:35:43.615) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() start
D/(18:35:43.630) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(18:35:43.630) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() called
D/(18:35:43.630) KurobaEx-fdroid | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:43.630) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() done
D/(18:35:43.630) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(18:35:43.634) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() end, took 15.832077ms
D/(18:35:43.661) KurobaEx-fdroid | CrashReportActivity: CrashReportActivity launched
E/(18:35:43.672) KurobaEx-fdroid | CrashReportActivity: Got new exception: java.lang.IllegalStateException
D/(18:35:43.677) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(18:35:43.678) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 13.769us, callbacks count: 2
D/(18:35:44.018) KurobaEx-fdroid | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 19809, max allowed posts amount: 75000
D/(18:35:44.354) KurobaEx-fdroid | BookmarksRepository: initialize() -> 26 took 315.444923ms
D/(18:35:44.356) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() called
D/(18:35:44.356) KurobaEx-fdroid | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:44.356) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() done
D/(18:35:44.357) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() done. Loaded 26 bookmarks and 5 active bookmarks
D/(18:35:44.357) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() end, took 764.946847ms
D/(18:35:44.361) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(18:35:44.361) KurobaEx-fdroid | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:44.362) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(18:35:44.362) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(18:35:44.362) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() end, took 746.895077ms
D/(18:35:44.369) KurobaEx-fdroid | SiteRepository: initializeSites() -> 27 took 5.213462ms
D/(18:35:44.370) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(18:35:44.370) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(18:35:44.370) KurobaEx-fdroid | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:44.370) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(18:35:44.370) KurobaEx-fdroid | SiteRepository: allSitesLoadedInitializer initialized
D/(18:35:44.412) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://yeshoney.xyz/'
D/(18:35:44.423) KurobaEx-fdroid | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 10820, max allowed threads amount: 12500
D/(18:35:44.424) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(18:35:44.424) KurobaEx-fdroid | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:44.424) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(18:35:44.429) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(18:35:44.440) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://endchan.net/'
D/(18:35:44.451) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(18:35:44.452) KurobaEx-fdroid | FilterWatcherCoordinator: chanFilterManager.listenForFiltersChanges() new filterEvent
D/(18:35:44.457) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(26)
D/(18:35:44.459) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(18:35:44.460) KurobaEx-fdroid | BookmarksRepository: persist(26) took 3.090461ms
E/(18:35:44.463) KurobaEx-fdroid | SiteManager: Unknown site descriptor: SD{yuki.la}
D/(18:35:44.483) KurobaEx-fdroid | BookmarksManager: subscriptions=2
D/(18:35:44.483) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(18:35:44.484) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() watchBackground is false, stopping background watcher
D/(18:35:44.484) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(18:35:44.485) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() calling startWatchingIfNotWatchingYet()
D/(18:35:44.487) KurobaEx-fdroid | BookmarkForegroundWatcher: working == true, calling updateBookmarksWorkerLoop()
D/(18:35:44.488) KurobaEx-fdroid | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=811ms)
E/(18:35:44.489) KurobaEx-fdroid | SiteManager: Unknown site descriptor: SD{archive.rebeccablacktech.com}
D/(18:35:44.527) KurobaEx-fdroid | Dvach: Using domain: 'https://2ch.hk/'
D/(18:35:44.531) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(18:35:44.531) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:44.531) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(18:35:44.531) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 27 sites
D/(18:35:44.531) KurobaEx-fdroid | SiteManager: loadSitesInternal() end, took 952.002462ms
D/(18:35:44.531) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(18:35:44.539) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 22 took 37.283692ms
D/(18:35:44.540) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 22 bookmark groups
D/(18:35:44.541) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 56.583692ms
D/(18:35:44.803) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 1636 took 249.668385ms
D/(18:35:44.809) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(18:35:44.809) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(18:35:44.809) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(18:35:44.810) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 1636 boards
D/(18:35:44.810) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 1.218332692s
D/(18:35:45.489) KurobaEx-fdroid | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=1812ms)
D/(18:35:46.490) KurobaEx-fdroid | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=2813ms)
D/(18:35:47.491) KurobaEx-fdroid | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=3814ms)
D/(18:35:48.492) KurobaEx-fdroid | BookmarkForegroundWatcher: updateBookmarksWorkerLoop() app was not long enough in the foreground to start updating bookmarks (foregroundTime=4815ms)

```
Additional information
```
------------------------------
Android API Level: 31
App Version: v1.3.21
Phone Model: samsung SM-A315G
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 00:00:09.598
System animations state: duration: 1.0, transition: 1.0, window: 1.0
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 2
CloudFlare force preload enabled: true
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 12; SM-A315G Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.21
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 128
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/7E5C-D903%3ASyncthing%20%2FPhoto%20Internet%2F4chan
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: true
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: true
------------------------------

```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/fb742eb1a1a5f00beee87f3ebe59c9555c0c1439
