### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException start > length()

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#837]
Stacktrace
```
java.lang.StringIndexOutOfBoundsException: start > length()
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:853)
	at java.lang.StringBuilder.replace(StringBuilder.java:263)
	at com.github.k1rakishou.kurobaexlite.helpers.notifications.ReplyNotificationsHelper$setupReplyNotificationsStyle$parsedReplyComments$1.invokeSuspend(ReplyNotificationsHelper.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

```

Logs
```
D/KurobaExLite | MainActivity: onCreate() start isFreshStart: true
D/KurobaExLite | MainActivityIntentHandler: Got intent with action 'android.intent.action.MAIN'
V/KurobaExLite | ApplicationVisibilityManager: onActivityStarted('MainActivity', 192629115)
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^
V/KurobaExLite | BaseViewModel: ViewModel MainActivityViewModel created
D/KurobaExLite | LoadBookmarks: Loaded 1 bookmarks from database
D/KurobaExLite | LoadBookmarks: activeBookmarksCount is greater than zero (1) restarting the work
D/KurobaExLite | BookmarkBackgroundWatcherWorker: restartBackgroundWork() called tag=com.github.k1rakishou.kurobaexlite.helpers.BookmarkWatcher_Production
D/KurobaExLite | BookmarkBackgroundWatcherWorker: restartBackgroundWork() enqueued work with tag com.github.k1rakishou.kurobaexlite.helpers.BookmarkWatcher_Production, backgroundIntervalMillis=1000
D/KurobaExLite | GlobalUiInfoManager: UiInfoManager initialization started
D/KurobaExLite | GlobalUiInfoManager: UiInfoManager initialization finished
D/KurobaExLite | UpdateManager: Can't check updates, last check was not too long ago, time until next check: 18:18:49.742
V/KurobaExLite | NavigationRouter: pushScreen(HomeScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(HomeScreen, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(HomeScreen, AddToNavStack)
V/KurobaExLite | NavigationRouter: pushScreen(CatalogScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(CatalogScreen, AddToNavStack)
V/KurobaExLite | NavigationRouter: pushScreen(ThreadScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(ThreadScreen, AddToNavStack)
V/KurobaExLite | BaseViewModel: ViewModel CatalogScreenViewModel created
V/KurobaExLite | BaseViewModel: ViewModel ThreadScreenViewModel created
V/KurobaExLite | BaseViewModel: ViewModel HomeScreenViewModel created
V/KurobaExLite | NavigationRouter: pushScreen(BookmarksScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(BookmarksScreen, AddToNavStack)
D/KurobaExLite | ThreadScreenViewModel: loadPrevVisitedThread() got LastVisitedThread(threadDescriptor=ThreadDescriptor(4chan/vst/1249683), title=is it normal for american civil war to happen so early in V3?) from loadNavigationHistory
D/KurobaExLite | CatalogScreenViewModel: loadPrevVisitedCatalog() got LastVisitedCatalog(catalogDescriptor=CatalogDescriptor(4chan/vmg)) from loadNavigationHistory
V/KurobaExLite | ComposeScreen: onCreated(CatalogScreen, AddToNavStack)
V/KurobaExLite | ComposeScreen: onCreated(ThreadScreen, AddToNavStack)
V/KurobaExLite | BaseViewModel: ViewModel ReplyLayoutViewModel created
D/KurobaExLite | ReplyLayoutViewModel: processReplyLayoutStates() replyLayoutStateKeys is empty, doing cleanup()
D/KurobaExLite | LocalFilePicker: cleanup() removed 0 directories with files
V/KurobaExLite | BaseViewModel: ViewModel HistoryScreenViewModel created
D/KurobaExLite | LoadNavigationHistory: loadFromDatabase(256)
V/KurobaExLite | BaseViewModel: ViewModel BookmarksScreenViewModel created
V/KurobaExLite | ComposeScreen: onCreated(BookmarksScreen, AddToNavStack)
D/KurobaExLite | LoadNavigationHistory: loaded 20 navigation elements
D/KurobaExLite | BookmarkBackgroundWatcherWorker: doWork() start
D/KurobaExLite | FetchThreadBookmarkInfo: bookmarkDescriptorsCount=1
V/KurobaExLite | Chan4DataSource: loadBookmarkData() url='https://a.4cdn.org/vst/thread/1251028.json'
V/KurobaExLite | NavigationRouter: pushScreen(CatalogSelectionScreen)
V/KurobaExLite | ComposeScreen: onStartCreating(CatalogSelectionScreen, AddToNavStack)
V/KurobaExLite | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() currentlyOpenedThread=null, unreadNotificationsGrouped=0
D/KurobaExLite | ReplyNotificationsHelper: showNotificationForReplies(unreadNotificationsGroupedCount=0, currentlyOpenedThread=null)
D/KurobaExLite | ReplyNotificationsHelper: showNotificationForReplies() unreadNotificationsGrouped are empty
D/KurobaExLite | ReplyNotificationsHelper: closeAllNotifications() visibleNotifications are empty
V/KurobaExLite | ComposeScreen: onCreated(CatalogSelectionScreen, AddToNavStack)
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/vst/thread/1251028.json' start
V/KurobaExLite | BaseViewModel: ViewModel CatalogSelectionScreenViewModel created
D/KurobaExLite | GetSiteBoardList: siteKey=4chan, forceReload=false
D/KurobaExLite | GetSiteBoardList: Reading from database...
D/KurobaExLite | GetSiteBoardList: Reading from database... SUCCESS
D/KurobaExLite | GetSiteBoardList: Got catalogs from the database: count=78
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/vst/thread/1251028.json' end
D/KurobaExLite | FetchThreadBookmarkInfo: fetchThreadBookmarkInfo stats: total results=1, errorsCount=0, alreadyDeletedCount=0, notFoundOnServerCount=0, badStatusCount=0, successCount=1
V/KurobaExLite | FetchThreadBookmarkInfo: updateSingleBookmark() threadBookmark=ThreadBookmark(threadDescriptor=ThreadDescriptor(4chan/vst/1251028), seenPostsCount=11, threadRepliesCount=19, threadLastViewedPostPostDescriptor=PostDescriptor(4chan/vst/1251028/1251111,0), threadLastPostPostDescriptor=PostDescriptor(4chan/vst/1251028/1251384,0), threadBookmarkReplies={PostDescriptor(4chan/vst/1251028/1251231,0)=ThreadBookmarkReply(postDescriptor=PostDescriptor(4chan/vst/1251028/1251231,0), repliesTo=PostDescriptor(4chan/vst/1251028/1251096,0), alreadyNotified=false, alreadySeen=false, alreadyRead=false, time=2022-11-04T17:23:13.263+03:00, commentRaw=<a href="#p1251034" class="quote)}, title=Which CK game is bet, thumbnailUrl=https://i.4cdn.org/vst/1667537729791360s.jpg, stickyThread=NotSticky, state=[WATCHING], createdOn=2022-11-04T10:46:48.239+03:00)
D/KurobaExLite | PersistBookmarks: persisting 1 bookmarks
D/KurobaExLite | CatalogPagesRepository: loading catalog page info for CatalogDescriptor(4chan/vst)
V/KurobaExLite | Chan4DataSource: loadCatalogPagesData() url='https://a.4cdn.org/vst/threads.json'
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/vst/threads.json' start
D/KurobaExLite | FetchThreadBookmarkInfo: processResultsInternal() success, activeBookmarksCount: 1, took: 18.473698ms
D/KurobaExLite | BookmarkBackgroundWatcherWorker: fetchThreadBookmarkInfo() success
D/KurobaExLite | BookmarkBackgroundWatcherWorker: activeBookmarksCount: 1 restarting the work
D/KurobaExLite | BookmarkBackgroundWatcherWorker: restartBackgroundWork() called tag=com.github.k1rakishou.kurobaexlite.helpers.BookmarkWatcher_Production
D/KurobaExLite | BookmarkBackgroundWatcherWorker: restartBackgroundWork() enqueued work with tag com.github.k1rakishou.kurobaexlite.helpers.BookmarkWatcher_Production, backgroundIntervalMillis=30000
D/KurobaExLite | BookmarkBackgroundWatcherWorker: doWork() end
V/KurobaExLite | UndispatchedCoroutine: suspendConvertWithJsonAdapter() url='https://a.4cdn.org/vst/threads.json' end
D/KurobaExLite | CatalogPagesRepository: loaded 151 threads with page info for CatalogDescriptor(4chan/vst)
V/KurobaExLite | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() currentlyOpenedThread=null, unreadNotificationsGrouped=1
D/KurobaExLite | ReplyNotificationsHelper: showNotificationForReplies(unreadNotificationsGroupedCount=1, currentlyOpenedThread=null)
D/KurobaExLite | ReplyNotificationsHelper: setupChannels() called
D/KurobaExLite | ReplyNotificationsHelper: setupChannels() creating com.github.k1rakishou.kurobaexlite_reply_summary_notifications_channel channel
D/KurobaExLite | ReplyNotificationsHelper: setupChannels() creating com.github.k1rakishou.kurobaexlite_reply_summary_silent_notifications_channel channel
D/KurobaExLite | ReplyNotificationsHelper: setupChannels() creating com.github.k1rakishou.kurobaexlite_replies_notifications_channel channel
D/KurobaExLite | ReplyNotificationsHelper: showSummaryNotification() onlyHasNewRepliesFromCurrentThread=false, unreadNotificationsGrouped = 1, unseenRepliesCount=1, newRepliesCount=1
D/KurobaExLite | ReplyNotificationsHelper: showSummaryNotification() Using R.drawable.ic_stat_notify_alert icon
D/KurobaExLite | ReplyNotificationsHelper: showSummaryNotification() Using REPLY_SUMMARY_NOTIFICATION_CHANNEL_ID
D/KurobaExLite | ReplyNotificationsHelper: Using vibration
D/KurobaExLite | ReplyNotificationsHelper: showSummaryNotification() notificationManagerCompat.notify() called
D/KurobaExLite | ReplyNotificationsHelper: showNotificationsForAndroidOreoAndAbove() called
D/KurobaExLite | ReplyNotificationsHelper: Loaded 1 bookmarks
D/KurobaExLite | ReplyNotificationsHelper: Loaded 1 thumbnail bitmaps
E/KurobaExLite | KurobaExLiteApplication: [Global] Unhandled exception in coroutine: 'null', error: java.lang.StringIndexOutOfBoundsException: start > length()
E/KurobaExLite | KurobaExLiteApplication: 	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:853)
E/KurobaExLite | KurobaExLiteApplication: 	at java.lang.StringBuilder.replace(StringBuilder.java:263)
E/KurobaExLite | KurobaExLiteApplication: 	at com.github.k1rakishou.kurobaexlite.helpers.notifications.ReplyNotificationsHelper$setupReplyNotificationsStyle$parsedReplyComments$1.invokeSuspend(ReplyNotificationsHelper.kt:35)
E/KurobaExLite | KurobaExLiteApplication: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/KurobaExLite | KurobaExLiteApplication: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/KurobaExLite | KurobaExLiteApplication: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
E/KurobaExLite | KurobaExLiteApplication: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
E/KurobaExLite | KurobaExLiteApplication: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
D/KurobaExLite | CrashReportActivity: Got new exception: java.lang.StringIndexOutOfBoundsException
V/KurobaExLite | ApplicationVisibilityManager: onActivityStarted('CrashReportActivity', 212204663)
D/KurobaExLite | ApplicationVisibilityManager: ^^^ App went foreground ^^^

```
Additional information
```
Android API Level: 31
App Version: 1.0.7
Phone Model: Xiaomi M2102J20SG
Flavor type: Production
isSlowDevice: false
MemoryClass: 256
App running time: 00:00:03.929
System animations info: duration: 0.0, transition: 0.0, window: 0.0

```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/KurobaExLite/commit/ddc7e930d84609c5d66036d326a9611b67862ab1
