### ISSUE TITLE
java.lang.IllegalStateException Failed to create ExoPlayer cache directory! exoPlayerCacheDir=/data/user/0/com.github.k1rakishou.chan.fdroid/cache/exo_player_cache

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#846]
Stacktrace
```
java.lang.IllegalStateException: Failed to create ExoPlayer cache directory! exoPlayerCacheDir=/data/user/0/com.github.k1rakishou.chan.fdroid/cache/exo_player_cache
	at com.github.k1rakishou.common.AppConstants.getExoPlayerCacheDir(AppConstants.kt:5)
	at com.github.k1rakishou.chan.features.media_viewer.helper.ExoPlayerCache$actualCache$2.invoke(ExoPlayerCache.kt:2)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at com.github.k1rakishou.chan.features.media_viewer.MediaViewerController.access$awaitThumbnailLoadedAndShowViewPager(MediaViewerController.kt:50)
	at com.github.k1rakishou.chan.features.media_viewer.MediaViewerController$awaitThumbnailLoadedAndShowViewPager$1.invokeSuspend(MediaViewerController.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Controller_MediaViewerController), StandaloneCoroutine{Cancelling}@e7332f0, Dispatchers.Main]

```

Logs
```
D/(17:31:50.716) KurobaEx-fdroid | ChanTicker: StopTicker
D/(17:31:50.716) KurobaEx-fdroid | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/x/33274840}
D/(17:31:50.829) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/x/33274840}, waiting 0ms
D/(17:31:50.829) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action begin
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: onChanTickerTick(TD{4chan/x/33274840})
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: normalLoad() start
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/x/33274840}
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: showLoading=false
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(17:31:50.829) KurobaEx-fdroid | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(17:31:50.830) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action end
D/(17:31:50.830) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=1, nextWaitTimeSeconds=20
D/(17:31:50.885) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/x/33274840}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(17:31:50.885) KurobaEx-fdroid | ChanThreadManager: loadInternal() Requested thread /TD{4chan/x/33274840}/
D/(17:31:50.885) KurobaEx-fdroid | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/x/33274840}) begin
D/(17:31:50.886) KurobaEx-fdroid | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/x/33274840}) end, took 1.405990ms
D/(17:31:50.887) KurobaEx-fdroid | ChanThreadManager: loadInternal(), chanDescriptor=TD{4chan/x/33274840} preloadThreadInfo took 1.685833ms
D/(17:31:50.887) KurobaEx-fdroid | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/x/33274840}, UpdateCache) -> true
D/(17:31:50.897) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/x/thread/33274840.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{4chan/x/33274840}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader, postProcessFlags=null)
D/(17:31:50.910) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:50.911) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:50.927) KurobaEx-fdroid | BookmarkForegroundWatcher: updateBookmarkForOpenedThread() ChanSettings.watchEnabled() is false
D/(17:31:51.054) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:51.068) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/x/thread/33274840.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{4chan/x/33274840}, toParse=1, closed=false, deleted=false, archived=false, error=null}
D/(17:31:51.070) KurobaEx-fdroid | NormalPostLoader: persistPosts(TD{4chan/x/33274840}, ChanReaderProcessor{chanDescriptor=TD{4chan/x/33274840}, toParse=1, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(17:31:51.071) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=TD{4chan/x/33274840}, postsToParseCount=1)
D/(17:31:51.073) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/x/33274840}) -> parsedPosts=1
D/(17:31:51.074) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=TD{4chan/x/33274840}, filtersCount=0)
D/(17:31:51.074) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/x/33274840}, postsToParseSize=1), internalIds=57, filters=0
D/(17:31:51.076) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateThreadPosts() 1 posts differ from the cache (total posts=1)
D/(17:31:51.078) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{4chan/x/33274840}, postsCount=1)
D/(17:31:51.079) KurobaEx-fdroid | ChanThread: Thread cache (TD{4chan/x/33274840}) Added 0 new posts, updated 1 posts, marked as deleted 0 posts. sortAndRecalculationDuration=122.969us
D/(17:31:51.079) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateMany(TD{4chan/x/33274840}) -> 1
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/x/thread/33274840.json.
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Network request execution took 156.101510ms.
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Json reading took 14.269219ms.
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Store new posts took 3.704688ms (stored 1 posts).
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Parse posts took 1.797501ms (parsed 1 out of 57 posts).
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Filter processing took 27.239us (filers count: 0).
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 206/5000.
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Current thread cached posts count: 57
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Threads with more than one post count: (1/5), total cached threads count: 150.
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total local processing time: 19.798647ms
D/(17:31:51.096) KurobaEx-fdroid | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/x/33274840}) begin
D/(17:31:51.096) KurobaEx-fdroid | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/x/33274840}) end
D/(17:31:51.096) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(), descriptor=TD{4chan/x/33274840} postloadThreadInfo took 122.136us
D/(17:31:51.096) KurobaEx-fdroid | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/x/33274840}} (currentChanDescriptor=TD{4chan/x/33274840})
D/(17:31:51.096) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/x/33274840}
D/(17:31:51.096) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(17:31:51.099) KurobaEx-fdroid | KotlinExts: awaitUntilGloballyLaidOut(com.github.k1rakishou.chan.ui.view.LoadView{278d169 V.E...... ........ 0,0-1080,1920 #7f0a0204 app:id/loadview}) widthOk=true, width=1080, heightOk=true, height=1920
D/(17:31:51.100) KurobaEx-fdroid | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/x/33274840}
D/(17:31:51.100) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/x/33274840}, waiting 20000ms
D/(17:31:51.104) KurobaEx-fdroid | PostHideHelper: processPostFilters(TD{4chan/x/33274840}) start
D/(17:31:51.105) KurobaEx-fdroid | PostHideHelper: processPostFilters(TD{4chan/x/33274840}) end (hiddenPostsCount=0, removedPostsCount=0, normalPostsCount=57, total=57)
D/(17:31:51.107) KurobaEx-fdroid | ThreadCellData: runPreloading() start
D/(17:31:51.107) KurobaEx-fdroid | ThreadCellData: runPreloading() startingPosition=52, dataListSize=57
D/(17:31:51.108) KurobaEx-fdroid | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=57
D/(17:31:51.108) KurobaEx-fdroid | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/x/33274840}) -> true applyFilterDuration=1.721146ms, setThreadPostsDuration=3.059218ms, totalDuration=8.779375ms
D/(17:31:51.111) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData(TD{4chan/x/33274840}) end, took 14.732812ms
D/(17:31:51.111) KurobaEx-fdroid | ThreadPresenter: normalLoad() end
D/(17:31:51.111) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/x/33274840}, postHidesCount=0, postFiltersCount=0)
D/(17:31:51.112) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:51.112) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:51.122) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async called
D/(17:31:51.122) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=256
D/(17:31:51.124) KurobaEx-fdroid | NavHistoryLocalSource: persist(navHistoryStack.size=256)
D/(17:31:51.142) KurobaEx-fdroid | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(17:31:51.143) KurobaEx-fdroid | Dependency Injection: Using DnsSelector.Mode.SYSTEM
D/(17:31:51.151) KurobaEx-fdroid | ThreadCellData: runPreloading() end, took 43.945260ms
D/(17:31:51.203) KurobaEx-fdroid | HistoryNavigationRepository: persist(256) took 78.646197ms
D/(17:31:51.250) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async finished
D/(17:31:52.072) KurobaEx-fdroid | PostExtraContentLoader: fetchExtraLinkInfo('https://youtu.be/bKS_QIPet-k') fetcher=YoutubeMediaServiceExtraInfoFetcher
D/(17:31:52.072) KurobaEx-fdroid | PostExtraContentLoader: fetchExtraLinkInfo('https://youtu.be/Tzh_QJGs1DY') fetcher=YoutubeMediaServiceExtraInfoFetcher
D/(17:31:56.073) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(17:31:56.077) KurobaEx-fdroid | KotlinExts: awaitUntilGloballyLaidOut(com.github.k1rakishou.chan.ui.view.LoadView{278d169 V.E...... ........ 0,0-1080,1920 #7f0a0204 app:id/loadview}) widthOk=true, width=1080, heightOk=true, height=1920
D/(17:31:56.079) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(333)
D/(17:31:56.084) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/x/33274840}, postHidesCount=0, postFiltersCount=0)
D/(17:31:56.085) KurobaEx-fdroid | PostHideHelper: processPostFilters(TD{4chan/x/33274840}) start
D/(17:31:56.085) KurobaEx-fdroid | PostHideHelper: processPostFilters(TD{4chan/x/33274840}) end (hiddenPostsCount=0, removedPostsCount=0, normalPostsCount=57, total=57)
D/(17:31:56.086) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:56.087) KurobaEx-fdroid | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=57
D/(17:31:56.087) KurobaEx-fdroid | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/x/33274840}) -> true applyFilterDuration=1.934531ms, setThreadPostsDuration=1.184583ms, totalDuration=10.394166ms
D/(17:31:56.088) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/x/33274840})
D/(17:31:56.088) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(17:31:56.088) KurobaEx-fdroid | BookmarksRepository: persist(333) took 8.643177ms
D/(17:31:56.089) KurobaEx-fdroid | ThreadCellData: runPreloading() start
D/(17:31:56.089) KurobaEx-fdroid | ThreadCellData: runPreloading() startingPosition=52, dataListSize=57
D/(17:31:56.089) KurobaEx-fdroid | BookmarksManager: subscriptions=4
D/(17:31:56.089) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(17:31:56.119) KurobaEx-fdroid | ThreadCellData: runPreloading() end, took 29.908385ms
D/(17:31:56.187) KurobaEx-fdroid | ChanThreadViewableInfoLocalSource: Updating ChanThreadViewableInfo for TD{4chan/x/33274840}
D/(17:31:56.718) KurobaEx-fdroid | MediaViewerActivity: threadMedia() postDescriptorList.size=57
D/(17:31:56.719) KurobaEx-fdroid | ThreadMediaParcelableHolder: fromThreadDescriptor() 57 <= 250
D/(17:31:56.866) KurobaEx-fdroid | MediaViewerController: offscreenPageLimit=1
D/(17:31:56.877) KurobaEx-fdroid | MediaViewerActivity: handleNewIntent() action=com.github.k1rakishou.chan.fdroid_internal.view.thread.media.action
D/(17:31:56.929) KurobaEx-fdroid | MediaViewerActivity: handleNewIntent() viewModel.showMedia() -> true
E/(17:31:57.249) KurobaEx-fdroid | Chan: Unhandled exception in thread: main
E/(17:31:57.249) KurobaEx-fdroid | Chan: java.lang.IllegalStateException: Failed to create ExoPlayer cache directory! exoPlayerCacheDir=/data/user/0/com.github.k1rakishou.chan.fdroid/cache/exo_player_cache
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.common.AppConstants.getExoPlayerCacheDir(AppConstants.kt:5)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.media_viewer.helper.ExoPlayerCache$actualCache$2.invoke(ExoPlayerCache.kt:2)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.media_viewer.MediaViewerController.access$awaitThumbnailLoadedAndShowViewPager(MediaViewerController.kt:50)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.media_viewer.MediaViewerController$awaitThumbnailLoadedAndShowViewPager$1.invokeSuspend(MediaViewerController.kt)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at android.os.Handler.handleCallback(Handler.java:739)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at android.os.Looper.loop(Looper.java:158)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7224)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/(17:31:57.249) KurobaEx-fdroid | Chan: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Controller_MediaViewerController), StandaloneCoroutine{Cancelling}@e7332f0, Dispatchers.Main]
D/(17:31:58.282) KurobaEx-fdroid | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(17:31:58.467) KurobaEx-fdroid | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.fdroid/files/kurobaex_theme_light.json) does not exist on the disk
D/(17:31:58.510) KurobaEx-fdroid | ChanPostRepository: ChanPostRepository.initialize()
D/(17:31:58.551) KurobaEx-fdroid | SiteManager: SiteManager.initialize()
D/(17:31:58.552) KurobaEx-fdroid | SiteManager: loadSitesInternal() start
D/(17:31:58.553) KurobaEx-fdroid | BoardManager: BoardManager.initialize()
D/(17:31:58.555) KurobaEx-fdroid | BoardManager: loadBoardsInternal() start
D/(17:31:58.555) KurobaEx-fdroid | BookmarksManager: BookmarksManager.initialize()
D/(17:31:58.555) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(17:31:58.556) KurobaEx-fdroid | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(17:31:58.556) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() start
D/(17:31:58.556) KurobaEx-fdroid | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(17:31:58.558) KurobaEx-fdroid | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(17:31:58.560) KurobaEx-fdroid | ArchivesManager: ArchivesManager.initialize()
D/(17:31:58.560) KurobaEx-fdroid | ChanFilterManager: ChanFilterManager.initialize()
D/(17:31:58.561) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() start
D/(17:31:58.561) KurobaEx-fdroid | Chan: Application initialization took 963ms
D/(17:31:58.562) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() start
D/(17:31:58.630) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(17:31:58.630) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() called
D/(17:31:58.630) KurobaEx-fdroid | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:58.630) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() done
D/(17:31:58.631) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(17:31:58.633) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() end, took 70.227448ms
D/(17:31:58.673) KurobaEx-fdroid | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 10731, max allowed posts amount: 75000
D/(17:31:58.792) KurobaEx-fdroid | CrashReportActivity: CrashReportActivity launched
E/(17:31:58.817) KurobaEx-fdroid | CrashReportActivity: Got new exception: java.lang.IllegalStateException
D/(17:31:58.836) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(17:31:58.836) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 73.906us, callbacks count: 2
D/(17:31:58.862) KurobaEx-fdroid | BookmarksRepository: initialize() -> 333 took 171.146927ms
D/(17:31:58.863) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() called
D/(17:31:58.864) KurobaEx-fdroid | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:58.864) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() done
D/(17:31:58.865) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() done. Loaded 333 bookmarks and 332 active bookmarks
D/(17:31:58.870) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() end, took 310.882552ms
D/(17:31:58.874) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(17:31:58.874) KurobaEx-fdroid | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:58.874) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(17:31:58.875) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(17:31:58.875) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() end, took 312.527449ms
D/(17:31:58.890) KurobaEx-fdroid | SiteRepository: initializeSites() -> 25 took 17.796511ms
D/(17:31:58.893) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(17:31:58.893) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(17:31:58.893) KurobaEx-fdroid | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:58.893) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(17:31:58.893) KurobaEx-fdroid | SiteRepository: allSitesLoadedInitializer initialized
D/(17:31:58.907) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://yeshoney.xyz/'
D/(17:31:58.917) KurobaEx-fdroid | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 10729, max allowed threads amount: 12500
D/(17:31:58.918) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(17:31:58.918) KurobaEx-fdroid | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:58.918) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(17:31:58.947) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(17:31:58.952) KurobaEx-fdroid | LynxchanSite: Using domain: 'https://endchan.net/'
D/(17:31:59.053) KurobaEx-fdroid | Dvach: Using domain: 'https://2ch.hk/'
D/(17:31:59.071) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(17:31:59.071) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:59.071) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(17:31:59.071) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(17:31:59.071) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 25 sites
D/(17:31:59.071) KurobaEx-fdroid | SiteManager: loadSitesInternal() end, took 519.067708ms
D/(17:31:59.105) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 78 took 20.614687ms
D/(17:31:59.107) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(17:31:59.107) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(17:31:59.107) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(17:31:59.107) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 78 boards
D/(17:31:59.107) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 552.228853ms
D/(17:31:59.300) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(17:31:59.305) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(333)
D/(17:31:59.309) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(17:31:59.309) KurobaEx-fdroid | BookmarksRepository: persist(333) took 4.749739ms
D/(17:31:59.439) KurobaEx-fdroid | BookmarksManager: subscriptions=2
D/(17:31:59.439) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(17:31:59.451) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(17:31:59.451) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(17:31:59.451) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(17:31:59.504) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 13 took 47.271823ms
D/(17:31:59.506) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 13 bookmark groups
D/(17:31:59.506) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 54.648230ms

```
Additional information
```
------------------------------
Android API Level: 23
App Version: v1.3.21
Phone Model: samsung SM-G870W
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: true, isLowRamDeviceForced: true
MemoryClass: 128
App running time: 00:00:13.661
System animations state: duration: 1.0, transition: 0.0, window: 1.0
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 6.0.1; SM-G870W Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.21
maxPostsCountInPostsCache: 5000
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3ADownload
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment]
See https://github.com/KurobaExReports/Reports/issues/847
